# memchash_key Update this
conf:
  # Start Time & End Time 
  start: 2014/01/14 14:00:00
  end:   2014/02/23 23:59:59
  second_period_start: 2014/01/19 00:00:00

  # Encounter rate adjustment based on remaining Stamina
  # Portion of stamina left (Empty=0 to Full=1)
  # Please put values in ascending order.
  # Currently can handle up to 3 values.
  # If they are smaller than this, they will be implemented appropriately.
  last_stamina_encount_rate:
    # stamina_appear_rate0
    - 0.1
    # stamina_appear_rate1
    - 0.3
    # stamina_appear_rate2
    - 0.5
  # Use point rankings?
  use_point_ranking: 1

  # Special Raid Items: Outside of the event period they are:
  raid_item:
    # Dragon's Egg
    -  1104
# Included in card intro list
special_cards:
  # Winged Embrace Mariaje
  - 260209
  # Fleeting Miracle Ashley
  - 350228
  # Hidden Feelings Celia
  - 140214
  # Anxious Love Rianje
  - 230210
  # Bold Heroine Nadi
  - 360201
  # Wolf Knight Von Kolt
  - 250186
  # Sahuagin Champion Zagreb
  - 240187
  # Beast Tamer Emady
  - 330202

# Special Boss Appearance Start Time Setup
# The boss will not start appearing until after the time below is reached.
boss_appear_limit:
  type:
    - 4
  start: '2014/01/14 14:00:00'

raid_battle:
  # Critical Factor
  critical_fact:
    1.5
  # Divine Water Flag
  usable_special_item:
    1
  # Usable period is linked to the shop set below.
  shinsui_shop_def: shinsui_sell
  # Divine Water Type Qty.
  item_fact:
    1.5
  # Stamina Cost List
  stamina:
    - 20
    - 40
    - 60
  # Stamina Adjustment
  stamina_correct:
    - 0.3
    - 0.7
    - 1.3
  # Stamina Cost Upon Escape
  escape_cost: 20
  # Cooperative Attack Bonus
  # Point bonus when attacking a boss that someone else discovered.
  cooperation_damage_bonus:
    1.2

  # Anti-Raid Boss Special Cards
  special_card:
    # Result Point Adjustment
    type_result_point:
#      1226: 1.2
#      1227: 1.2
#      1228: 1.2
#      1229: 1.2
#      # Labyrinth
#      1354: 1.5
#      1355: 1.5
#      1356: 1.5
#      1357: 1.5
#      # Talia
#      1358: 1.2
#      1359: 1.2
#      1360: 1.2
#      1361: 1.2

    # Damage Multiplier
    type_damage:

      # Winged Embrace Mariaje
      260209: 3
      261209: 6
      262209: 12
      263209: 25
      
      # Fleeting Miracle Ashley
      350228: 2
      351228: 4.5
      352228: 7
      359228: 15
      
      # Hidden Feelings Celia
      140214: 1.5
      141214: 3
      142214: 5
      149214: 11
      
      # Anxious Love Rianje
      230210: 1.2
      231210: 2
      232210: 3
      239210: 7
      
      # Bold Heroine Nadi
      360201: 3
      361201: 6
      362201: 12
      363201: 25
      
      # Wolf Knight Von Kolt
      250186: 2
      251186: 4.5
      252186: 7
      259186: 15      

    # Critical Multiplier
    #Not used this time, but in order to avoid errors we put in a dummy card with multipliers of 1.
#    type_critical:
#      # Pumpkin Princess
#      1181: 1
#      1182: 1
#      1183: 1
#      1184: 1

  # Special Anti-Raid Boss Cards
#  boss_special_card:
#    4: #boss_type
#      # 受け継がれし勇気ナディ
#      360201: 14
#      361201: 16
#      362201: 18
#      363201: 20
#    0: #boss_type
#      # 受け継がれし勇気ナディ
#      360201: 7
#      361201: 8
#      362201: 9
#      363201: 10
#    1: #boss_type
#      # 受け継がれし勇気ナディ
#      360201: 7
#      361201: 8
#      362201: 9
#      363201: 10
#    2: #boss_type
#      # 受け継がれし勇気ナディ
#      360201: 7
#      361201: 8
#      362201: 9
#      363201: 10
#    3: #boss_type
#      # 受け継がれし勇気ナディ
#      360201: 7
#      361201: 8
#      362201: 9
#      363201: 10
#    5: #boss_type
#      # 受け継がれし勇気ナディ
#      360201: 7
#      361201: 8
#      362201: 9
#      363201: 10

# Rewards
reward:
  # MP Recovery (Recovery Amount: Ratio Based)
  recover_mp:
    10: 90
    20: 9
    30: 1

  # Stamina Recovery (Stamina Points Used Value Exceeded: Full Recovery)
  recover_stamina:
    0: 0
    60: 20
    180: 40

  # roulette Rewards
  roulette_bonus_lot: 75
  roulette_bonus:
    1:
      lot: 16
      type: stamina
      effect_fact: 0
      minute: 5
    2:
      lot: 16.5
      type: stamina
      effect_fact: 0.5
      minute: 10
    3:
      lot: 16
      type: exp
      effect_fact: 2
      minute: 5
    4:
      lot: 16.5
      type: exp
      effect_fact: 1.5
      minute: 10
    5:
      lot: 16
      type: boss
      effect_fact: 2
      minute: 5
    6:
      lot: 17
      type: boss
      effect_fact: 1.5
      minute: 10
    7:
      lot: 1.4
      type: item
      id: 22
      cnt: 1
    8:
      lot: 0.55
      type: item
      id: 22
      cnt: 2
    9:
      lot: 0.05
      type: item
      id: 22
      cnt: 3

  # Special Card Rewards based on number of boss victories
#  piece_collection_bonus:
#    # Counted Boss Type
#    type:
#      - 0
#      - 1
#      - 2
#      - 3
#      - 4
#      - 5
#    # Increase increment for number of Victories
#    piece_turn: 5
#    # Number of pieces gained
#    complete_cnt: 9
#    #piece Complete Rewards
#    complete_bonus:
#      1:
#        type: card
#        id: 350170
#        cnt: 1
#    bonus_limit: 4

  # Special Boss Victory Rewards
  smash_bonus:
    disp_name: 'Raid Boss'
    # Count Boss Type
    type:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    #Boss Victory Rewards
    array:
      5:
        type: item
        id: 4
        cnt: 1
      10:
        type: item
        id: 22
        cnt: 1
      15:
        type: item
        id: 22
        cnt: 1
      20:
        type: card
        id: 612
        cnt: 1
      25:
        type: item
        id: 22
        cnt: 1
      30:
        type: item
        id: 22
        cnt: 1
      35:
        type: item
        id: 4
        cnt: 1
      40:
        type: item
        id: 22
        cnt: 1
      45:
        type: item
        id: 4
        cnt: 2
      50:
        type: item
        id: 22
        cnt: 1
      55:
        type: item
        id: 22
        cnt: 1
      60:
        type: item
        id: 22
        cnt: 1
      65:
        type: item
        id: 4
        cnt: 2
      70:
        type: card
        id: 613
        cnt: 1
      75:
        type: item
        id: 22
        cnt: 1
      80:
        type: card
        id: 614
        cnt: 1
      85:
        type: item
        id: 4
        cnt: 2
      90:
        type: item
        id: 22
        cnt: 3
    repeat:
      start: 100
      interval: 10
      reward:
        type: item
        id: 4
        cnt: 3


## Floor N Reached Rewards:　Kerapy （R）330082
#  quest_boss:
#    25:
#      comment: 'Crystal Tower　Stage 25 Clear Reward'
#      reward:
#        -
#          type: card
#          id: 330082
#          cnt: 1
#    50:
#      comment: 'Crystal Tower　Stage 50 Clear Reward'
#      reward:
#        -
#          type: card
#          id: 330082
#          cnt: 1
#    75:
#      comment: 'Crystal Tower　Stage 75 Clear Reward'
#      reward:
#        -
#          type: card
#          id: 330082
#          cnt: 1
#    100:
#      comment: 'Crystal Tower　Stage 100 Clear Reward'
#      reward:
#        -
#          type: card
#          id: 330082
#          cnt: 1
#  # Boss Victory Thanks
#  present_send:
#    comment: 'Thanks for helping out!'
#    list:
#      -
#        type: card
#        id: 612
#        cnt: 1
# Thanks message default text.
greet:
  default_message:
    # The program is set up so that if multiple strings are included the game will select one randomly.
    - 'Thanks for joining the battle!'
