# 配布番号
compensation:
  # 個人ランキング
  type_personal_ranker: 12072259
  # 個人キリ番
  type_personal_just: 12072258
  # 騎士団ランキング
  type_guild_ranker: 12072257
  # 神水変換
  type_item_change: 12072275
  # 受け取り有効期間
  valid_time: '2012/07/30 23:59:59'

# 個人
personal:
  ranker:
    # 1~10位まで
    1:
      subject: '堕天の呪術師 個人ランキング1～10位報酬'
      body: '堕天の呪術師 個人ランキング1～10位報酬です。'
      comment: '堕天の呪術師 個人ランキング1～10位報酬です。'
      items:
        # バハムート
        - type: card
          id: 651
        # ほんとはSRチケット
        - type: item
          id : 16
          cnt : 1
    # 11~50位まで
    3:
      subject: '堕天の呪術師 個人ランキング11～50位報酬'
      body: '堕天の呪術師 個人ランキング11～50位報酬です。'
      comment: '堕天の呪術師 個人ランキング11～50位報酬です。'
      items:
        # バハムート
        - type: card
          id: 651
        # ほんとはHRチケット
        - type: item
          id : 15
          cnt : 1
    # 51~200位まで
    4:
      subject: '堕天の呪術師 個人ランキング51～200位報酬'
      body: '堕天の呪術師 個人ランキング51～200位報酬です。'
      comment: '堕天の呪術師 個人ランキング51～200位報酬です。'
      items:
        # ポセイドン
        - type: card
          id: 655
        # ほんとはHRチケット
        - type: item
          id : 15
          cnt : 1
    # 201~500位まで
    7:
      subject: '堕天の呪術師 個人ランキング201～500位報酬'
      body: '堕天の呪術師 個人ランキング201～500位報酬です。'
      comment: '堕天の呪術師 個人ランキング201～500位報酬です。'
      items:
        # ポセイドン
        - type: card
          id: 655
        # レアチケット2枚
        - type: item
          id : 1
          cnt : 2
    # 501~2000位まで
    9:
      subject: '堕天の呪術師 個人ランキング501～2000位報酬'
      body: '堕天の呪術師 個人ランキング501～2000位報酬です。'
      comment: '堕天の呪術師 個人ランキング501～2000位報酬です。'
      items:
        # アスラ
        - type: card
          id: 659
        # レアチケット2枚
        - type: item
          id : 1
          cnt : 2
    # 2001~5000位まで
    10:
      subject: '堕天の呪術師 個人ランキング2001～5000位報酬'
      body: '堕天の呪術師 個人ランキング2001～5000位報酬です。'
      comment: '堕天の呪術師 個人ランキング2001～5000位報酬です。'
      items:
        # レアチケット1枚
        - type: item
          id : 1
          cnt : 1
        # 霊水3個
        - type: item
          id : 2
          cnt : 3
    # 5001~12000位まで
    13:
      subject: '堕天の呪術師 個人ランキング5001～12000位報酬'
      body: '堕天の呪術師 個人ランキング5001～12000位報酬です。'
      comment: '堕天の呪術師 個人ランキング5001～12000位報酬です。'
      items:
        # 霊水3個
        - type: item
          id : 2
          cnt : 3
    # 12001~30000位まで
    16:
      subject: '堕天の呪術師 個人ランキング12001～30000位報酬'
      body: '堕天の呪術師 個人ランキング12001～30000位報酬です。'
      comment: '堕天の呪術師 個人ランキング12001～30000位報酬です。'
      items:
        # 霊水2個
        - type: item
          id : 2
          cnt : 2
    # 30001位以降
    # マイナスは必ず最後に置くこと
    -1:
      subject: '堕天の呪術師 個人ランキング30001位～報酬'
      body: '堕天の呪術師 個人ランキング30001位～報酬です。'
      comment: '堕天の呪術師 個人ランキング30001位～報酬です。'
      items:
        # 霊水1個
        - type: item
          id : 2
          cnt : 1


  just:
    17:
      subject: '堕天の呪術師 個人ランキングキリ番200位報酬'
      body: '堕天の呪術師 個人ランキングキリ番200位報酬です。'
      comment: '堕天の呪術師 個人ランキングキリ番200位報酬です。'
      items:
        # バハムート
        - type: card
          id: 651
        # ほんとはHRチケット
        - type: item
          id : 15
          cnt : 1
    5:
      subject: '堕天の呪術師 個人ランキングキリ番500位報酬'
      body: '堕天の呪術師 個人ランキングキリ番500位報酬です。'
      comment: '堕天の呪術師 個人ランキングキリ番500位報酬です。'
      items:
        # バハムート
        - type: card
          id: 651
        # ほんとはHRチケット
        - type: item
          id : 15
          cnt : 1
    7:
      subject: '堕天の呪術師 個人ランキングキリ番2000位報酬'
      body: '堕天の呪術師 個人ランキングキリ番2000位報酬です。'
      comment: '堕天の呪術師 個人ランキングキリ番2000位報酬です。'
      items:
        # バハムート
        - type: card
          id: 651
        # ほんとはHRチケット
        - type: item
          id : 15
          cnt : 1
    9:
      subject: '堕天の呪術師 個人ランキングキリ番5000位報酬'
      body: '堕天の呪術師 個人ランキングキリ番5000位報酬です。'
      comment: '堕天の呪術師 個人ランキングキリ番5000位報酬です。'
      items:
        # バハムート
        - type: card
          id: 651
        # ほんとはHRチケット
        - type: item
          id : 15
          cnt : 1
# 騎士団
guild:
  ranker:
    # 1~10位まで
    2:
      bottom: 100000
      subject: '堕天の呪術師 騎士団ランキング1～10位報酬'
      body: '堕天の呪術師 騎士団ランキング1～10位報酬です。'
      comment: '堕天の呪術師 騎士団ランキング1～10位報酬です。'
      items:
        # ポセイドン
        - type: card
          id: 655
        # キングx2
        - type: card
          id: 614
        - type: card
          id: 614
        # マダム
        - type: card
          id: 613
        # ダンディ
        - type: card
          id: 612
    # 11~50位まで
    3:
      bottom: 1000
      subject: '堕天の呪術師 騎士団ランキング11～50位報酬'
      body: '堕天の呪術師 騎士団ランキング11～50位報酬です。'
      comment: '堕天の呪術師 騎士団ランキング11～50位報酬です。'
      items:
        # アスラ
        - type: card
          id: 659
        # キング
        - type: card
          id: 614
        # マダム
        - type: card
          id: 613
        # ダンディ
        - type: card
          id: 612
    # 51~100位まで
    4:
      subject: '堕天の呪術師 騎士団ランキング51～100位報酬'
      body: '堕天の呪術師 騎士団ランキング51～100位報酬です。'
      comment: '堕天の呪術師 騎士団ランキング51～100位報酬です。'
      items:
        # アスラ
        - type: card
          id: 659
        # マダム
        - type: card
          id: 613
        # ダンディ
        - type: card
          id: 612
    # 101~300位まで
    8:
      subject: '堕天の呪術師 騎士団ランキング101～300位報酬'
      body: '堕天の呪術師 騎士団ランキング101～300位報酬です。'
      comment: '堕天の呪術師 騎士団ランキング101～300位報酬です。'
      items:
        # マダム
        - type: card
          id: 613
        # ダンディ
        - type: card
          id: 612
    # 301~1000位まで
    9:
      subject: '堕天の呪術師 騎士団ランキング301～1000位報酬'
      body: '堕天の呪術師 騎士団ランキング301～1000位報酬です。'
      comment: '堕天の呪術師 騎士団ランキング301～1000位報酬です。'
      items:
        # ダンディ
        - type: card
          id: 612

change:
  subject: '神水からの霊水への変換'
  body: '神水からの霊水への変換です。'
  comment: '神水からの霊水への変換です。'
  items:
    - type: item
      id: 2
      # cnt を入れるべし
