#####################################
###########<<  総合報酬  >>############
#####################################

# レイド報酬有効？
enable: 1

# 配布番号
# 【注意点】：後半のキーとかぶっちゃだめよ！
compensation:
  # 総合個人ランキング
  type_personal_ranker: 310714300
  # 総合個人キリ番
  type_personal_just: 310714301
  # 総合騎士団ランキング
  type_guild_ranker: 310714302
  # 神水変換
  type_item_change: 310714303
  # 受け取り有効期間
  valid_time: 2014/09/01 23:59:59

display_card_ids:
  # Vertulio
  - 150222
  # Advisor Layla
  - 140219

display_card_ids_personal:
  # Vertulio
  - 150222

display_card_ids_guild:
  # Advisor Layla
  - 140219

# 報酬配布時コメントの置換に使用
event_name: 'Egoistic Princess'

# 総合個人
personal:
  ranker:
    # 1~10位
    10:
      rank_title: '1-10th Place'
      subject: 'Egoistic Princess Reward for 1-10th Place in Total Personal Ranking'
      body: 'Egoistic Princess <br/>Reward for 1-10th Place in Total Personal Ranking.'
      comment: 'Egoistic Princess <br/>Reward for 1-10th Place in Total Personal Ranking.'
      items:
        # MRall Choice
        - type: item
          id : 1718
          cnt : 1
        # Vertulio
        - type: card
          id : 150222
          cnt : 1
        # HR Ticket
        - type: item
          id : 7
          cnt : 1
    # 11-50位
    50:
      rank_title: '11-50th Place'
      subject: 'Egoistic Princess Reward for 1-50th Place in Total Personal Ranking'
      body: 'Egoistic Princess <br/>Reward for 1-50th Place in Total Personal Ranking.'
      comment: 'Egoistic Princess <br/>Reward for 1-50th Place in Total Personal Ranking.'
      items:
        # MRall Choice
        - type: item
          id : 1719
          cnt : 1
        # Vertulio
        - type: card
          id : 150222
          cnt : 1
        # HR Ticket
        - type: item
          id : 7
          cnt : 1
    # 51-150位
    150:
      rank_title: '51-150th Place'
      subject: 'Egoistic Princess Reward for 51-150th Place in Total Personal Ranking'
      body: 'Egoistic Princess <br/>Reward for 51-150th Place in Total Personal Ranking.'
      comment: 'Egoistic Princess Reward for 51-150th Place in Total Personal Ranking.'
      items:
        # Vertulio
        - type: card
          id : 150222
          cnt : 1
        # HR Ticket
        - type: item
          id : 7
          cnt : 1
    # 151-500位
    500:
      rank_title: '151-500th Place'
      subject: 'Egoistic Princess Reward for 151-500th Place in Total Personal Ranking'
      body: 'Egoistic Princess <br/>Reward for 151-500th Place in Total Personal Ranking.'
      comment: 'Egoistic Princess Reward for 151-500th Place in Total Personal Ranking.'
      items:
        # Vertulio
        - type: card
          id : 150222
          cnt : 1
        # R Ticket
        - type: item
          id : 1
          cnt : 1
    # 501-1500位
    1500:
      rank_title: '501-1500th Place'
      subject: 'Egoistic Princess Reward for 501-1500th Place in Total Personal Ranking'
      body: 'Egoistic Princess <br/>Reward for 501-1500th Place in Total Personal Ranking.'
      comment: 'Egoistic Princess Reward for 501-1500th Place in Total Personal Ranking.'
      items:
        # HR Ticket
        - type: item
          id : 7
          cnt : 1
        # R Ticket
        - type: item
          id : 1
          cnt : 1
    # 1501-5000位
    5000:
      rank_title: '1501-5000th Place'
      subject: 'Egoistic Princess Reward for 1501-5000th Place in Total Personal Ranking'
      body: 'Egoistic Princess <br/>Reward for 1501-5000th Place in Total Personal Ranking.'
      comment: 'Egoistic Princess Reward for 1501-5000th Place in Total Personal Ranking.'
      items:
        # R Ticket
        - type: item
          id : 1
          cnt : 1
#     # 50001位以下
#    -1:
#      rank_title: '50001以下'
#      subject: 'ワガママ姫は挫けない 総合個人ランキング50001位以下報酬'
#      body: 'ワガママ姫は挫けない 総合個人ランキング50001位以下報酬です。'
#      comment: 'ワガママ姫は挫けない 総合個人ランキング50001位以下報酬です。'
#      items:
#        # ギル
#        - type: virtual_money
#          id : 0
#          cnt : 10000

#総合個人ランキング キリ番
  just:
    333:
      subject: 'Egoistic Princess Reward for Lucky 333rd Place in Total Personal Ranking'
      body: 'Egoistic Princess <br/>Reward for Lucky 333rd Place in Total Personal Ranking.'
      comment: 'Egoistic Princess Reward for Lucky 333rd Place in Total Personal Ranking.'
      items:
        # Vertulio
        - type: card
          id : 150222
          cnt : 1
    555:
      subject: 'Egoistic Princess Reward for Lucky 555rd Place in Total Personal Ranking'
      body: 'Egoistic Princess <br/>Reward for Lucky 555rd Place in Total Personal Ranking.'
      comment: 'Egoistic Princess Reward for Lucky 555rd Place in Total Personal Ranking.'
      items:
        # Vertulio
        - type: card
          id : 150222
          cnt : 1
    1111:
      subject: 'Egoistic Princess Reward for Lucky 1111rd Place in Total Personal Ranking'
      body: 'Egoistic Princess <br/>Reward for Lucky 1111rd Place in Total Personal Ranking.'
      comment: 'Egoistic Princess Reward for Lucky 1111rd Place in Total Personal Ranking.'
      items:
        # Vertulio
        - type: card
          id : 150222
          cnt : 1
    2222:
      subject: 'Egoistic Princess Reward for Lucky 2222rd Place in Total Personal Ranking'
      body: 'Egoistic Princess <br/>Reward for Lucky 2222rd Place in Total Personal Ranking.'
      comment: 'Egoistic Princess Reward for Lucky 2222rd Place in Total Personal Ranking.'
      items:
        # Vertulio
        - type: card
          id : 150222
          cnt : 1
    3333:
      subject: 'Egoistic Princess Reward for Lucky 3333rd Place in Total Personal Ranking'
      body: 'Egoistic Princess <br/>Reward for Lucky 3333rd Place in Total Personal Ranking.'
      comment: 'Egoistic Princess Reward for Lucky 3333rd Place in Total Personal Ranking.'
      items:
        # Vertulio
        - type: card
          id : 150222
          cnt : 1
# クラン
guild:
  ranker:
    # 1~1位
    1:
      bottom: 100000
      rank_title: '1st Place'
      subject: 'Egoistic Princess  Reward for 1st Place in Total Guild Ranking'
      body: 'Egoistic Princess <br/>Reward for 1st Place in Total Guild Ranking.'
      comment: 'Egoistic Princess Reward for 1st Place in Total Guild Ranking.'
      items:
        # MRall Choice
        - type: item
          id : 1718
          cnt : 1
    # 2~4
    4:
      bottom: 100000
      rank_title: '2-4th Place'
      subject: 'Egoistic Princess Reward for 2-4th Place in Total Guild Ranking'
      body: 'Egoistic Princess <br/>Reward for 2-5th Place in Total Guild Ranking'
      comment: 'Egoistic Princess Reward for 2-5th Place in Total Guild Ranking'
      items:
        # MRall Lucky Box
        - type: item
          id: 1719
          cnt: 1

    # 5~50
    50:
      bottom: 100000
      rank_title: '5-50 Place'
      subject: 'Egoistic Princess Reward for 5-50th Place in Total Guild Ranking'
      body: 'Egoistic Princess <br/>Reward for 5-50th Place in Total Guild Ranking'
      comment: 'Egoistic Princess Reward for 5-50th Place in Total Guild Ranking'
      items:
        # Vertulio
        - type: card
          id: 150222
          cnt: 1
    # 51~300位
    300:
      bottom: 1000
      rank_title: '51-300 Place'
      subject: 'Egoistic Princess Reward for 51-300th Place in Total Guild Ranking'
      body: 'Egoistic Princess <br/>Reward for 51-300th Place in Total Guild Ranking'
      comment: 'Egoistic Princess Reward for 51-300th Place in Total Guild Ranking'
      items:
        # Advisor Layla
        - type: card
          id: 140219
          cnt: 1
#    # 3001〜
#    -1:
#      rank_title: '3001以下'
#      subject: 'ワガママ姫は挫けない 総合騎士団ランキング3001位以下報酬'
#      body: 'ワガママ姫は挫けない 総合騎士団ランキング3001位以下報酬です'
#      comment: 'ワガママ姫は挫けない 総合騎士団ランキング3001位以下報酬です'
#      items:
#        # レアチケ
#        - type: item
#          id: 1
#          cnt: 1

#秘薬を霊水へ変更
change:
  subject: "Exchange of Hero's Crystals for Stamina Potion."
  body: "You exchanged Hero's Crystals for Stamina Potion."
  comment: "You exchanged Hero's Crystals for Stamina Potion."
  items:
    - type: item
      id: 2
      cnt: 1
      # cnt を入れるべし

#宝箱が作られてないユーザーの一括報酬配布
trouble_reward:
  reward_mst: 
    #boss_type:0 レアボス
    0:
      #reward_type:1 最多ダメージ
      1:
        type: item
        id: 5
        cnt: 1
      #reward_type:2 攻撃者
      2:
        type: card
        id: 612
        cnt: 1
      #reward_type:3 発見者
      3:
        type: item
        id: 5
        cnt: 1
      #reward_type:4 撃破者
      4:
        type: item
        id: 6
        cnt: 1
    #boss_type:1 ノーマルボス
    1:
      #reward_type:1 最多ダメージ
      1:
        type: item
        id: 5
        cnt: 1
      #reward_type:2 攻撃者
      2:
        type: gacha_p
        id: 0
        cnt: 200
      #reward_type:3 発見者
      3:
        type: virtual_money
        id: 0
        cnt: 2000
      #reward_type:4 撃破者
      4:
        type: item
        id: 6
        cnt: 1
    #boss_type:2 ノーマルボス
    2:
      #reward_type:1 最多ダメージ
      1:
        type: item
        id: 5
        cnt: 1
      #reward_type:2 攻撃者
      2:
        type: gacha_p
        id: 0
        cnt: 200
      #reward_type:3 発見者
      3:
        type: virtual_money
        id: 0
        cnt: 2000
      #reward_type:4 撃破者
      4:
        type: item
        id: 6
        cnt: 1
    #boss_type:3 ノーマルボス
    3:
      #reward_type:1 最多ダメージ
      1:
        type: item
        id: 5
        cnt: 1
      #reward_type:2 攻撃者
      2:
        type: gacha_p
        id: 0
        cnt: 200
      #reward_type:3 発見者
      3:
        type: virtual_money
        id: 0
        cnt: 2000
      #reward_type:4 撃破者
      4:
        type: item
        id: 6
        cnt: 1
    #boss_type:4 裏ボス
    4:
      #reward_type:1 最多ダメージ
      1:
        type: item
        id: 7
        cnt: 1
      #reward_type:2 攻撃者
      2:
        type: card
        id: 613
        cnt: 1
      #reward_type:3 発見者
      3:
        type: item
        id: 4
        cnt: 1
      #reward_type:4 撃破者
      4:
        type: item
        id: 36
        cnt: 1
    #boss_type:5 ボーナスボス
    5:
      #reward_type:1 最多ダメージ
      1:
        type: item
        id: 1
        cnt: 1
      #reward_type:2 攻撃者
      2:
        type: card
        id: 612
        cnt: 1
      #reward_type:3 発見者
      3:
        type: item
        id: 5
        cnt: 1
      #reward_type:4 撃破者
      4:
        type: item
        id: 6
        cnt: 1
