# レイド報酬有効？
enable: 1

# 配布番号
compensation:
  # 個人ランキング
  type_personal_ranker: 201303291
  # 個人キリ番
  type_personal_just: 201303292
  # クランランキング
  type_guild_ranker: 201303293
  # 神水変換
  type_item_change: 201303294
  # 受け取り有効期間
  valid_time: '2013/04/14 23:59'
  
display_card_ids:
  # Fire Wyrm
  - 160089
  - 260500
  - 360502
  # Starfire Dragon
  - 150503
  - 250503
  - 350097
  - 130501 #Whelpling
  - 140502 #Blackheart

display_card_ids_personal:
  # Fire Wyrm
  - 160089
  - 260500
  - 360502
  # Starfire Dragon
  - 150503
  - 250503
  - 350097
  - 130501 #Whelpling
  - 140502 #Blackheart

display_card_ids_guild:
  # Starfire Dragon
  - 150503
  - 250503
  - 350097
  - 130501 #Whelpling

# 報酬配布時コメントの置換に使用
event_name: 'Dragon''s Domain'

# 個人
personal:
  ranker:
    # 1~10位
    10:
      rank_title: '1~10'
      subject: '$event_name Individual Rankings 1~10'
      body: '$event_name Individual Rankings 1~10'
      comment: '$event_name Individual Rankings 1~10'
      items:
        # Fire Wyrm Choice Box
        - type: item
          id: 99
          cnt: 2
    # 11-50位
    50:
      rank_title: '11〜50'
      subject: '$event_name Individual Rankings 11~50'
      body: '$event_name Individual Rankings 11~50'
      comment: '$event_name Individual Rankings 11~50'
      items:
        # Fire Wyrm Choice Box
        - type: item
          id: 99
          cnt: 1
    # 51-100位
    100:
      rank_title: '51-100'
      subject: '$event_name Individual Rankings 51~100'
      body: '$event_name Individual Rankings 51~100'
      comment: '$event_name Individual Rankings 51~100'
      items:
        # Golden Starlight Dragon Choice Box
        - type: item
          id: 100
          cnt: 2
    # 101-200位
    200:
      rank_title: '101-200'
      subject: '$event_name Individual Rankings 101~200'
      body: '$event_name Individual Rankings 101~200'
      comment: '$event_name Individual Rankings 101~200'
      items:
        # Golden Starlight Dragon Choice Box
        - type: item
          id: 100
          cnt: 1
        # Rare Ticket
        - type: item
          id : 1
          cnt : 2
    # 201-300位
    300:
      rank_title: '201-300'
      subject: '$event_name Individual Rankings 201~300'
      body: '$event_name Individual Rankings 201~300'
      comment: '$event_name Individual Rankings 201~300'
      items:
        # Blackheart Dragon Choice Box
        - type: item
          id : 97
          cnt : 2
        # Rare Ticket
        - type: item
          id : 1
          cnt : 1
    # 301-500位
    500:
      rank_title: '301-500'
      subject: '$event_name Individual Rankings 301~500'
      body: '$event_name Individual Rankings 301~500'
      comment: '$event_name Individual Rankings 301~500'
      items:
        # Blackheart Dragon Choice Box
        - type: item
          id : 97
          cnt : 1
        # Rare Ticket
        - type: item
          id : 1
          cnt : 1
    # 501-700位
    700:
      rank_title: '501-700'
      subject: '$event_name Individual Rankings 501~700'
      body: '$event_name Individual Rankings 501~700'
      comment: '$event_name Individual Rankings 501~700'
      items:
        # Whelpling Choice Box
        - type: item
          id : 98
          cnt : 3
        # [Personal Use] Stamina Potion
        - type: item
          id : 4
          cnt : 1
    # 701-1000位
    1000:
      rank_title: '701-1000'
      subject: '$event_name Individual Rankings 701~1000'
      body: '$event_name Individual Rankings 701~1000'
      comment: '$event_name Individual Rankings 701~1000'
      items:
        # Whelpling Choice Box
        - type: item
          id : 98
          cnt : 2
        # [Personal Use] Stamina Potion
        - type: item
          id : 4
          cnt : 1
    # 1001-2000位
    2000:
      rank_title: '1001-2000'
      subject: '$event_name Individual Rankings 1001~2000'
      body: '$event_name Individual Rankings 1001~2000'
      comment: '$event_name Individual Rankings 1001~2000'
      items:
        # Whelpling Choice Box
        - type: item
          id : 98
          cnt : 1
    # 2001-5000位
    5000:
      rank_title: '2001-5000'
      subject: '$event_name Individual Rankings 2001~5000'
      body: '$event_name Individual Rankings 2001~5000'
      comment: '$event_name Individual Rankings 2001~5000'
      items:
        # [Personal Use] Stamina Potion
        - type: item
          id : 4
          cnt : 1
        # Rare Ticket
        - type: item
          id : 1
          cnt : 1

#     # 50001位以下
#    -1:
#      rank_title: '50001以下'
#      subject: '暴竜の血戦 個人ランキング50001位以下報酬'
#      body: '暴竜の血戦 個人ランキング50001位以下報酬です。'
#      comment: '暴竜の血戦 個人ランキング50001位以下報酬です。'
#      items:
#        # ギル
#        - type: virtual_money
#          id : 0
#          cnt : 10000

#個人ランキング キリ番
  just:
    333:
      subject: '$event_name Lucky 333'
      body: '$event_name Lucky 333'
      comment: '$event_name Lucky 333'
      items:
        # Golden Starlight Dragon Choice Box
        - type: item
          id: 100
          cnt: 1
    555:
      subject: '$event_name Lucky 555'
      body: '$event_name Lucky 555'
      comment: '$event_name Lucky 555'
      items:
        # Golden Starlight Dragon Choice Box
        - type: item
          id: 100
          cnt: 1
    1111:
      subject: '$event_name Lucky 1111'
      body: '$event_name Lucky 1111'
      comment: '$event_name Lucky 1111'
      items:
        # Golden Starlight Dragon Choice Box
        - type: item
          id: 100
          cnt: 1
    2222:
      subject: '$event_name Lucky 2222'
      body: '$event_name Lucky 2222'
      comment: '$event_name Lucky 2222'
      items:
        # Golden Starlight Dragon Choice Box
        - type: item
          id: 100
          cnt: 1
    3333:
      subject: '$event_name Lucky 3333'
      body: '$event_name Lucky 3333'
      comment: '$event_name Lucky 3333'
      items:
        # Golden Starlight Dragon Choice Box
        - type: item
          id: 100
          cnt: 1
# クラン
guild:
  ranker:
    # 1~10位
    10:
      bottom: 100000
      rank_title: '1~10'
      subject: '$event_name Guilds 1~10'
      body: '$event_name Guilds 1~10'
      comment: '$event_name Guilds 1~10'
      items:
        # Golden Starlight Dragon Choice Box
        - type: item
          id: 100
          cnt: 1
        # Power Crystal Lv.3
        - type: card
          id: 614
          cnt: 1
        # Power Crystal Lv.2
        - type: card
          id: 613
          cnt: 1
        # Power Crystal Lv.1
        - type: card
          id: 612
          cnt: 1
    # 11~50位
    50:
      bottom: 50000
      rank_title: '11~50'
      subject: '$event_name Guilds 11~50'
      body: '$event_name Guilds 11~50'
      comment: '$event_name Guilds 11~50'
      items:
        # Golden Starlight Dragon Choice Box
        - type: item
          id: 100
          cnt: 1
    # 51~100位
    100:
      bottom: 30000
      rank_title: '51~100'
      subject: '$event_name Guilds 51~100'
      body: '$event_name Guilds 51~100'
      comment: '$event_name Guilds 51~100'
      items:
        # Whelpling Choice Box
        - type: item
          id: 98
          cnt: 1
        # Power Crystal Lv.1
        - type: card
          id: 612
          cnt: 1
    # 101~300位
    300:
      bottom: 10000
      rank_title: '101~300'
      subject: '$event_name Guilds 101~300'
      body: '$event_name Guilds 101~300'
      comment: '$event_name Guilds 101~300'
      items:
        # Whelpling Choice Box
        - type: item
          id: 98
          cnt: 1
    # 301~1000位
    1000:
      bottom: 5000
      rank_title: '301~1000'
      subject: '$event_name Guilds 301~1000'
      body: '$event_name Guilds 301~1000'
      comment: '$event_name Guilds 301~1000'
      items:
        # 強化クリスタルLv.1
        - type: card
          id: 612
          cnt: 1
#    # 3001〜
#    -1:
#      rank_title: '3001以下'
#      subject: '暴竜の血戦 騎士団ランキング3001位以下報酬'
#      body: '暴竜の血戦 騎士団ランキング3001位以下報酬です'
#      comment: '暴竜の血戦 騎士団ランキング3001位以下報酬です'
#      items:
#        # レアチケ
#        - type: item
#          id: 1
#          cnt: 1

#秘薬を霊水へ変更
change:
  subject: 'Trade from Hero''s Crystal to Stamina Potion'
  body: 'Trade from Hero''s Crystal to Stamina Potion'
  comment: 'Trade from Hero''s Crystal to Stamina Potion'
  items:
    - type: item
      id: 2
      cnt: 1
      # cnt を入れるべし