#招待
invite:
  - type: 1 #招待 第1弾
    start: '2012/11/29 11:00:00'
    end: '2013/01/15 11:59:59'
    # 招待者りわーど
    invite_reward_card:
      0:
        type: card
        id: 230051
    invite_reward:
      0:
        type: item
        id: 4
        cnt: 1
      1:
        type: gacha_p
        cnt: 200
    # 招待者りわーどコメント
    invite_reward_comment:
      "招待キャンペーン1弾の報酬です。"
    # 招待された人りわーど
    invited_reward:
      0:
        type: item
        id: 4
        cnt: 3
      1:
        type: item
        id: 6
        cnt: 3
      2:
        type: gacha_p
        cnt: 2000
    invited_reward_comment:
      "招待キャンペーンの報酬です。"

#スタートダッシュ
start_dash:
  comp:
    last_date: 7
    reward:
      type: item
      id: 1
      cnt: 1
  reward:
    1:
      0:
        type: item
        id: 1
        cnt: 1
    2:
      0:
        type: virtual_money
        cnt: 3000
      1:
        type: item
        id: 2
        cnt: 1
      2:
        type: card
        id: 695
    3:
      0:
        type: virtual_money
        cnt: 3000
    4:
      0:
        type: card
        id: 695
    5:
      0:
        type: item
        id: 1
        cnt: 1
    6:
      0:
        type: gacha_p
        cnt: 1000
    7:
      0:
        type: virtual_money
        cnt: 5000
      1:
        type: card
        id: 695

#ユーザー登録❍万人突破記念
breakthrough:
  flag: 1
  campaign_id: 1
  comment: 'AppStore DL10万人突破記念のアイテムです。'
  reward:
    0:
      type: item
      id: 1
      cnt: 1
#breakthrough2:
#  flag: 1
#  campaign_id: 2
#  comment: 'AppStore DL20万人突破記念のアイテムです。'
#  reward:
#    0:
#      type: item
#      id: 1
#      cnt: 1
#    1:
#      type: item
#      id: 2
#      cnt: 3
#breakthrough3:
#  flag: 1
#  campaign_id: 3
#  comment: 'AppStore DL30万人突破記念のアイテムです。'
#  reward:
#    0:
#      type: item
#      id: 1
#      cnt: 1

normal_one_time1:
  flag: 1
  campaign_id: 1
  comment: 'コラボキャンペーンガーディアンです。'
  reward:
    0:
      type: card
      id: 230055
      cnt: 1

#無料ランキング❍位記念
ranking5:
  flag: 1
  campaign_id: 1
  comment: '無料ランキング5位突破記念です。'
  reward:
    0:
      type: item
      id: 3
      cnt: 1
ranking3:
  flag: 1
  campaign_id: 2
  comment: '無料ランキング3位突破記念です。'
  reward:
    0:
      type: card
      id: 612
      cnt: 1

ranking2:
  flag: 1
  campaign_id: 3
  comment: '無料ランキング2位突破記念です。'
  reward:
    0:
      type: card
      id: 230051
      cnt: 1
    1:
      type: item
      id: 1
      cnt: 1

#トップーセ-ルす❍位記念
#top3:
#  flag: 1
#  campaign_id: 1
#  comment: 'トップセールス3位突破記念です。'
#  reward:
#    0:
#      type: item
#      id: 1
#      cnt: 1
#top2:
#  flag: 0
#  campaign_id: 2
#  comment: 'トップセールス2位突破記念です。'
#  reward:
#    0:
#      type: item
#      id: 1
#      cnt: 1
#    1:
#      type: gacha_p
#      cnt: 3000
#top1:
#  flag: 0
#  campaign_id: 3
#  comment: 'トップセールス1位突破記念です。'
#  reward:
#    0:
#      type: item
#      id: 1
#      cnt: 1
#    1:
#      type: item
#      id: 2
#      cnt: 1
#    2:
#      type: gacha_p
#      cnt: 3000

#TOPセールス インフィニティ
#topsales_infinity:
#  flag: 1
#  campaign_id: 1
#  comment: 'クラバト×三国、同時ランクイン記念です。'
#  reward:
#    0:
#      type: card
#      id: 615
#      cnt: 1

#事前登録
preregist:
  flag: 1
  comment: '事前登録の報酬です。'
  reward:
    0:
      type: card
      id: 608
    1:
      type: item
      id: 1
      cnt: 1

#ポケラボリワード
pokelabo_reward:
  flag: 1
  campaign_id: 1
  #comment: '無料ランキング1位記念のアイテムです。'
  reward_card_cnt: 0,1,3,6,10
  reward_item_min: 11
  reward_item_max: 20
  reward_card:
    0:
      type: card
      id: 230051
  reward:
    0:
      type: gacha_p
      cnt: 200
    1:
      type: virtual_money
      cnt: 2000

#ポケラボリワード2
pokelabo_reward_2:
  flag: 1
  campaign_id: 0
  #comment: '無料ランキング1位記念のアイテムです。'
  reward_card_cnt: 0,1,3,6,10
  reward_item_min: 11
  reward_item_max: 20
  reward_card:
    0:
      type: card
      id: 695
  reward:
    0:
      type: gacha_p
      cnt: 200
    1:
      type: virtual_money
      cnt: 2000
