footer:
  2:
    default:
      link: '/adventure/'
      img: '/img/icon/footer_2n.png'
      text: '冒険'
    custom:
      start: 2012/08/02 10:00:00
      end: 2012/08/20 10:00:00
      link: '/raid_event/'
      img: '/img/icon/footer_7n.png'
      text: 'イベント'