grow_event:

  #################################################################
  # 期間設定
  #################################################################
  # イベント開催期間のstart-end
  start: '2013-03-01 20:00:00'
  end:   '2013-05-01 23:59:59'

  # イベントページ（開始前予告とか終了後画面とか）を表示させる期間のstart-end
  disp_start: '2013-03-01 00:00:00'
  disp_end:   '2013-05-12 23:59:59'

  #################################################################
  # 育成設定
  #################################################################
  # 育成合成
  grow_merge:
    # 一度に与えられる素材カード枚数
    material_max_num: 20
    # 与えられる最低レア度
    material_under_rarity: 30 # R以上(R最終進化は除く)
    # 親密度獲得経験値倍率(経験値に対する獲得倍率)
    grow_love_exp_rate: 0.1

    merge_per_rate: 1.3

    # 最期のレベルに到達した後、１レベルアップに必要な経験値数
    one_level_up_need_exp: 120000

#    need_exp_level_range:
#      1000: 1000000

    # 育成特別カードのid: 獲得経験値
    # card_mst_id: exp
    grow_special_card_exp:
      701: 2800
      702: 5200
      703: 8700


    # 育成素材に使用できないカード
    not_use_material_card_ids:
      #
      - 612
      - 613
      - 614
      - 777
      - 130123
      - 131123
      - 132123
      - 133123
      - 134123
      - 139123
      - 141123
      - 142123
      - 143123
      - 144123
      - 149123
      - 151123
      - 152123
      - 153123
      - 154123
      - 155123
      - 156123
      - 157123
      - 159123


    # HR以下で育成に特別に使用できるカードのmst_id
    can_use_under_rare_card:
    - 701
    - 120119
    - 121119
    - 122119
    - 129119
    - 120120
    - 121120
    - 122120
    - 129120
    - 310131
    - 311131
    - 312131
    - 319131
    - 210120
    - 211120
    - 212120
    - 219120
    - 110121
    - 111121
    - 112121
    - 119121



    # 育成ボーナスカード
    material_bonus:
      # 所持枚数によるアップ率
      # material_bonus内のup_type:
      #   クラン全体での該当カード所持枚数:
      #     アップ率
      up_type:
        1:
          1:
            2
          5:
            2.2
          10:
            2.5
          20:
            3

        2:
          1:
            1.2
          5:
            1.4
          10:
            1.6
          20:
            2

      # 育成ボーナス対象カード
      # type: - up_typeで指定した該当するタイプ
      #   card_mst_id: cnt(当該カードが1枚で何枚分に相当するか。進化カード等は複数枚に相当)
      up_card:
        1:
          -
            # 邪を滅す風のハスター
            350126: 1
            351126: 2
            352126: 3
            359126: 4

          -
            # 深淵より這い出る巫女
            250117: 1
            251117: 2
            252117: 3
            259117: 4

        2:
          -
            # ｢終わり｣をもたらす者
            140114: 1
            141114: 2
            142114: 3
            149114: 4

          -
            # 憎しみの権化アバドン
            140115: 1
            141115: 2
            142115: 3
            149115: 4

#  # 育成キャラ親密度
#  grow_love_point:
#    # 親密度
#    1:
#      # 累積経験値
#      0
#    2:
#      2000
#    3:
#      7800
#    4:
#      20000
#    5:
#      40000
#    6:
#      75000
#    7:
#      100000
#    8:
#      130000
#    9:
#      165000
#    10:
#      200000


  #################################################################
  # 育成報酬
  #################################################################
  reward_list:
    # 成長報酬
    grow_reward:
      category_type: 1
      reward_comment: '成長($chara_nameに進化)報酬です。'
      disp_card_mst_id: 130123
      reward:
        once:
          # 育成キャラLv
          # ヌトスLV40
          40:
            -
              type: virtual_money
              id: 0
              cnt: 30000
              img: 9
              title: 'リ・バース・ヌトス+'
              color: red
          # ヌトス+LV40
          79:
            -
              type: card
              id: 130123
              cnt: 1
              img: 11
              title: 'リ・バース・ヌトス++'
              color: red
          # ヌトス++LV40
          118:
            -
              type: gacha_p
              id: 0
              cnt: 5000
              img: 10
              title: 'リ・バース・ヌトス+3'
              color: red
          # ヌトス+3LV40
          157:
            -
              type: card
              id: 130123
              cnt: 1
              img: 11
              title: 'リ・バース・ヌトス+4'
              color: red
          # ヌトス+4LV40
          196:
            -
              type: item
              id: 4
              cnt: 1
              img: 1
              title: 'エウカリス・ヌトス'
              color: red
          # エウカリス・ヌトスLV50
          245:
            -
              type: card
              id: 130123
              cnt: 1
              img: 11
              title: 'エウカリス・ヌトス+'
              color: green
          # エウカリス・ヌトス+LV50
          294:
            -
              type: item
              id: 22
              cnt: 3
              img: 5
              title: 'エウカリス・ヌトス++'
              color: green
          # エウカリス・ヌトス++LV50
          343:
            -
              type: card
              id: 130123
              cnt: 1
              img: 11
              title: 'エウカリス・ヌトス+3'
              color: green
          # エウカリス・ヌトス+3LV50
          392:
            -
              type: item
              id: 4
              cnt: 2
              img: 2
              title: 'エウカリス・ヌトス+4'
              color: green
          # エウカリス・ヌトス+4LV50
          441:
            -
              type: card
              id: 130123
              cnt: 1
              img: 11
              title: 'シュヴァリエ・ヌトス'
              color: green
          # シュヴァリエ・ヌトスLV60
          500:
            -
              type: item
              id: 22
              cnt: 3
              img: 6
              title: 'シュヴァリエ・ヌトス+'
              color: purple
          # シュヴァリエ・ヌトス+LV60
          559:
            -
              type: card
              id: 130123
              cnt: 1
              img: 11
              title: 'シュヴァリエ・ヌトス++'
              color: purple
          # シュヴァリエ・ヌトス++LV60
          618:
            -
              type: item
              id: 4
              cnt: 3
              img: 3
              title: 'シュヴァリエ・ヌトス+3'
              color: purple
          # シュヴァリエ・ヌトス+3LV60
          677:
            -
              type: card
              id: 130123
              cnt: 1
              img: 11
              title: 'シュヴァリエ・ヌトス+4'
              color: purple
          # シュヴァリエ・ヌトス+4LV60
          736:
            -
              type: item
              id: 22
              cnt: 3
              img: 7
              title: 'シュヴァリエ・ヌトス+5'
              color: purple
          # シュヴァリエ・ヌトス+5LV60
          795:
            -
              type: card
              id: 130123
              cnt: 1
              img: 11
              title: 'シュヴァリエ・ヌトス+6'
              color: purple
          # シュヴァリエ・ヌトス+6LV60
          854:
            -
              type: item
              id: 4
              cnt: 4
              img: 4
              title: 'シュヴァリエ・ヌトス+7'
              color: purple
          # シュヴァリエ・ヌトス+7LV60
          913:
            -
              type: card
              id: 130123
              cnt: 1
              img: 8
              title: '【破邪】ヴァルキリー・ヌトス'
              color: purple
            -
              type: item
              id: 7
              cnt: 1
              img: 8
              title: '【破邪】ヴァルキリー・ヌトス'
              color: purple

        repeat:
          # インターバル:
          interval: 30
          items:
            -
              type: item
              id: 22
              cnt: 1
              img: 6
              title: '【破邪】ヴァルキリー・ヌトス'

    # 親密度報酬
    love_reward:
      category_type: 2
      reward_comment: '親密度$love_point到達報酬です。'
      disp_card_mst_id: 1272
      reward:
        # 親密度Lv
        2:
          -
            # ヌトス
            type: card
            id: 130123
            cnt: 1
        3:
          -
            # ヌトス
            type: card
            id: 130123
            cnt: 1
          -
            # 自分用進撃P全チャージ
            type: item
            id : 4
            cnt : 1
        4:
          -
            # ヌトス
            type: card
            id: 130123
            cnt: 2
          -
            # 騎士の鍵
            type: item
            id : 22
            cnt : 3
        5:
          -
            # ヌトス
            type: card
            id: 130123
            cnt: 1
          -
            # 強化クリスタルLv1
            type: card
            id: 612
            cnt: 1
        6:
          -
            # ヌトス
            type: card
            id: 130123
            cnt: 1
          -
            # 自分用進撃P全チャージx2
            type: item
            id : 4
            cnt : 2
        7:
          -
            # ヌトス
            type: card
            id: 130123
            cnt: 1
          -
            # 騎士の鍵
            type: item
            id : 22
            cnt : 3
        8:
          -
            # ヌトス
            type: card
            id: 130123
            cnt: 1
          -
            # 強化クリスタルLv2
            type: card
            id: 613
            cnt: 1
        9:
          -
            # ヌトス
            type: card
            id: 130123
            cnt: 1
          -
            # 自分用進撃P全チャージx3
            type: item
            id : 4
            cnt : 3
        10:
          -
            # ヌトスx2
            type: card
            id: 130123
            cnt: 1
          -
            # 騎士の鍵
            type: item
            id : 22
            cnt : 3

