---
driver_options:
  MYSQL_ATTR_DIRECT_QUERY: true
database:
  dbhosts:
    yggdrasill:
      hostname: immdevdb.ciguidpxtyhi.eu-west-1.rds.amazonaws.com
      dbname: ImmDev
      dbuser: AeriaDBUser
      dbpass: B3r1!n(0g4me$
    yggdrasill2:
      hostname: host_ip
      dbname: db_name
      dbuser: db_user
      dbpass: db_pass
    yggdrasill3:
      hostname: host_ip
      dbname: db_name
      dbuser: db_user
      dbpass: db_pass
    yggdrasill4:
      hostname: host_ip
      dbname: db_name
      dbuser: db_user
      dbpass: db_pass
  tables:
    # yggdrasill
    batch_log: yggdrasill
    user_account_cookie: yggdrasill
    adventure_area_mst: yggdrasill
    adventure_monster_mst: yggdrasill
    adventure_quest_mst: yggdrasill
    android_nonce: yggdrasill
    android_sales: yggdrasill
    attr_cnt: yggdrasill
    banner_mst: yggdrasill
    campaign_start_dash: yggdrasill
    event_button_mst: yggdrasill
    event_log: yggdrasill
    event_mst: yggdrasill
    gc_log: yggdrasill
    greeting_data: yggdrasill
    guild_bbs: yggdrasill
    guild_data: yggdrasill
    guild_join_subscription_data: yggdrasill
    guild_role_data: yggdrasill
    guild_role_mst: yggdrasill
    guild_scout_board_setup: yggdrasill
    guild_scout_subscription_data: yggdrasill
    guild_shogo_data: yggdrasill
    guild_shogo_mst: yggdrasill
    guild_user_data: yggdrasill
    information_guild: yggdrasill
    information_managerial: yggdrasill
    information_personal: yggdrasill
    invite_data: yggdrasill
    invite_event_mst: yggdrasill
    invite_reward_mst: yggdrasill
    invite_monster_chain_mst: yggdrasill
    item_data: yggdrasill
    item_log: yggdrasill
    item_mst: yggdrasill
    tieredspender_events: yggdrasill
    tieredspender_recharge_log: yggdrasill
    tieredspender_redemption_log: yggdrasill
    tieredspender_tiers: yggdrasill    
    login_bonus: yggdrasill
    login_image: yggdrasill
    market_point: yggdrasill
    market_point_android: yggdrasill
    medal_item_data: yggdrasill
    medal_item_log: yggdrasill
    medal_item_mst: yggdrasill
    mini_tutorial_data: yggdrasill
    mission_area_drop_item_pattern_mst: yggdrasill
    mission_area_mst: yggdrasill
    mission_boss_drop_item_pattern_mst: yggdrasill
    mission_boss_mst: yggdrasill
    mission_boss_user_log: yggdrasill
    mission_monster_pattern_mst: yggdrasill
    mission_stage_mst: yggdrasill
    mission_stage_user_data: yggdrasill
    mission_stage_user_log: yggdrasill
    mission_user_data: yggdrasill
    mission_story_mst: yggdrasill
    mission_story_character_mst: yggdrasill
    mysmon_to_guardian_data: yggdrasill
    opening_img: yggdrasill
    opening_quest_data: yggdrasill
    opening_quest_mst: yggdrasill
    opening_quest_state: yggdrasill
    partition_manager: yggdrasill
    payment_log: yggdrasill
    platform_login_history: yggdrasill
    pokelabo_reward: yggdrasill
    pokelabo_reward_2: yggdrasill
    pokelogger: yggdrasill
    pokelogger_data: yggdrasill
    preregist_data: yggdrasill
    purchase_history: yggdrasill
    purchase_money_data: yggdrasill
    purchase_request_history: yggdrasill
    purchase_request_history_android: yggdrasill
    quiz_mst: yggdrasill
    quiz_present_mst: yggdrasill
    sp_hello_comeback_user_data: yggdrasill
    stamp_data: yggdrasill
    stamp_data_log: yggdrasill
    stamp_event_mst: yggdrasill
    stamp_reward_mst: yggdrasill
    startdash_quest_data: yggdrasill
    startdash_quest_mst: yggdrasill
    startdash_quest_state: yggdrasill
    surveillance_user_data: yggdrasill
    theme_summons_flash_log_1: yggdrasill
    theme_summons_treasure_log_1: yggdrasill
    theme_summons_treasure_mst: yggdrasill
    theme_summons_user_data_1: yggdrasill
    user_account: yggdrasill
    user_data: yggdrasill
    user_login_info: yggdrasill
    user_onetime_event_data: yggdrasill
    user_quiz_state: yggdrasill
    user_session_data: yggdrasill
    user_shogo_data: yggdrasill
    user_shogo_mst: yggdrasill
    user_social_data: yggdrasill
    user_visit_data: yggdrasill
    daily_quest_data: yggdrasill
    daily_quest_mst: yggdrasill
    daily_quest_state: yggdrasill
    daily_quest: yggdrasill
    # yggdrasill2
    cvc_data_1: yggdrasill2
    cvc_rank_data_1: yggdrasill2
    cvc_user_data_1: yggdrasill2
    deck_data: yggdrasill2
    deck_detail_data: yggdrasill2
    gvg_action_history: yggdrasill2
    gvg_aid_effect_data: yggdrasill2
    gvg_aid_history: yggdrasill2
    gvg_battle_history: yggdrasill2
    gvg_battle_history_detail: yggdrasill2
    gvg_card_data: yggdrasill2
    gvg_combo_aid_bonus_data: yggdrasill2
    gvg_combo_aid_data: yggdrasill2
    gvg_combo_bonus_data: yggdrasill2
    gvg_combo_data: yggdrasill2
    gvg_combo_log: yggdrasill2
    gvg_data: yggdrasill2
    s_gvg_data: yggdrasill2
    gvg_guild_member_encourage: yggdrasill2
    gvg_life_recovery_history: yggdrasill2
    gvg_participating_log: yggdrasill2
    gvg_user_data: yggdrasill2
    gvg_counter_user: yggdrasill2
    gvg_participating_data: yggdrasill2
    gvg_skill_effect_data: yggdrasill2
    ragnarok_data: yggdrasill2
    ragnarok_spectator_log: yggdrasill2
    grow_chara_level_mst: yggdrasill2
    grow_chara_mst: yggdrasill2
    grow_chara_talk_mst: yggdrasill2
    grow_guild_data: yggdrasill2
    grow_guild_user_data: yggdrasill2
    grow_history_log: yggdrasill2
    grow_love_point_mst: yggdrasill2
    grow_love_reward_received_log: yggdrasill2
    grow_user_data: yggdrasill2
    grow_user_reward_data: yggdrasill2
    raid_area_mst: yggdrasill2
    raid_battle_log: yggdrasill2
    raid_boss_data: yggdrasill2
    raid_boss_mst: yggdrasill2
    raid_cluster_boss_appear_mst: yggdrasill2
    raid_cluster_mst: yggdrasill2
    raid_guild_data: yggdrasill2
    raid_guild_user_data_1: yggdrasill2
    raid_guild_user_data_2: yggdrasill2
    raid_guild_user_data_3: yggdrasill2
    raid_monster_mst: yggdrasill2
    raid_present_send_log: yggdrasill2
    raid_quest_mst: yggdrasill2
    raid_rank_distribution_guild: yggdrasill2
    raid_rank_distribution_personal: yggdrasill2
    raid_rareboss_rank_correct_mst: yggdrasill2
    raid_reward_mst: yggdrasill2
    raid_user_data: yggdrasill2
    raid_user_guild_point: yggdrasill2
    raid_user_help_data: yggdrasill2
    raid_user_help_list: yggdrasill2
    raid_user_quest_state: yggdrasill2
    raid_user_roulette_data: yggdrasill2
    raid_user_roulette_log: yggdrasill2
    raid_user_smash_cnt: yggdrasill2
    raid_user_smash_cnt_reward: yggdrasill2
    raid_user_treasure_data: yggdrasill2
    raid_reno_config: yggdrasill2
    raid_reno_area_mst: yggdrasill2
    raid_reno_boss_mst: yggdrasill2
    raid_reno_cluster_boss_appear_mst: yggdrasill2
    raid_reno_cluster_mst: yggdrasill2
    raid_reno_monster_mst: yggdrasill2
    raid_reno_quest_mst: yggdrasill2
    raid_reno_rareboss_rank_correct_mst: yggdrasill2
    raid_reno_reward_mst: yggdrasill2
    user_adventure_event: yggdrasill2
    user_adventure_quest_state: yggdrasill2
    rvr_data: yggdrasill2
    rvr_rank_team_a_data: yggdrasill2
    rvr_rank_team_b_data: yggdrasill2
    rvr_result_data: yggdrasill2
    rvr_user_data: yggdrasill2
    # yggdrasill3
    card_data: yggdrasill3
    card_evol_log: yggdrasill3
    card_merg_log: yggdrasill3
    card_mst: yggdrasill3
    card_sell_log: yggdrasill3
    card_skill_mst: yggdrasill3
    card_warehouse_data: yggdrasill3
    gacha_box_mst: yggdrasill3
    gacha_box_user_data: yggdrasill3
    gacha_box_user_data_log: yggdrasill3
    gacha_distribution_log: yggdrasill3
    gacha_hit_log: yggdrasill3
    gacha_log: yggdrasill3
    gacha_mst: yggdrasill3
    gacha_mst_name: yggdrasill3
    gacha_user_data: yggdrasill3
    gacha_ticket_use: yggdrasill3
    pictorial_data: yggdrasill3
    skill_data: yggdrasill3
    skill_merg_log: yggdrasill3
    skill_mst: yggdrasill3
    trade_clip: yggdrasill3
    trade_contract_log: yggdrasill3
    trade_entry: yggdrasill3
    trade_wish: yggdrasill3
    gacha_step_user_data: yggdrasill3
    gacha_step_log: yggdrasill3
    gacha_count_event: yggdrasill3
    sacrifice_count_event: yggdrasill3
    manastone_training_treasure_log: yggdrasill3
    manastone_training_treasure_mst: yggdrasill3
    manastone_training_user_data: yggdrasill3
    manastone_training_event: yggdrasill3
    # yggdrasill4
    access_log: yggdrasill4
    bbs_all_data: yggdrasill4
    bbs_all_reply_data: yggdrasill4
    error_js_log: yggdrasill4
    friend_list: yggdrasill4
    friend_list_pending: yggdrasill4
    information_compensation: yggdrasill4
    ipcountry_list: yggdrasill4
    lucky_egg_data: yggdrasill4
    lucky_egg_mst: yggdrasill4
    present_data: yggdrasill4
    present_receive_log: yggdrasill4
    rank_clan_data: yggdrasill4
    rank_clan_data_daily: yggdrasill4
    rank_clan_data_monthly: yggdrasill4
    rank_clan_data_weekly: yggdrasill4
    rank_clan_total_daily: yggdrasill4
    rank_clan_total_monthly: yggdrasill4
    rank_clan_total_weekly: yggdrasill4
    rank_clan_total_weekly_interim: yggdrasill4
    rank_personal_data: yggdrasill4
    rank_personal_data_daily: yggdrasill4
    rank_personal_data_weekly: yggdrasill4
    rank_personal_total: yggdrasill4
    rank_personal_total_daily: yggdrasill4
    rank_personal_total_weekly: yggdrasill4
    rank_status_data_daily: yggdrasill4
    rank_status_total_daily: yggdrasill4
    rank_card_data_1: yggdrasill4
    rank_card_data_2: yggdrasill4
    social_bonus_data: yggdrasill4
    admin_user: yggdrasill4
    admin_notification: yggdrasill4
    admin_change_name_log: yggdrasill4
    admin_user_inventory_delete_log: yggdrasill4
    admin_ban_log: yggdrasill4
    admin_unban_log: yggdrasill4
    urls: yggdrasill4
    cms_landing_pages: yggdrasill4
    campaign_code: yggdrasill4
    gacha_multi: yggdrasill4
    gacha_config: yggdrasill4
    card_merg_config: yggdrasill4
    gacha_box_config: yggdrasill4
    gacha_event: yggdrasill4
    maintenance: yggdrasill4
    cvc_event: yggdrasill4
    ragnarok_event: yggdrasill4
    preselection_event: yggdrasill4
    skill_bonus_config: yggdrasill4    
    gacha_step_event: yggdrasill4
    bonus_mst: yggdrasill4
    bonus_data: yggdrasill4
    strengthening_week_event: yggdrasill4
    crystal_recycle: yggdrasill4
    saturation_log: yggdrasill4
    amazon_sales: yggdrasill4
    gift_code_mst: yggdrasill4
    gift_code_log: yggdrasill4
    mission_config: yggdrasill4
    mat_api: yggdrasill4
    mat_api_android: yggdrasill4
    marketing_event: yggdrasill4
...
