conf:
  # 開始時間
  start: 2012/08/12 15:00:00
  # 終了時間
  end:   2012/11/31 23:59:59

special_cards:
  - 110040
  - 110041

sprigan_level:
  1:
    min: 0
    max: 4
  2:
    min: 3
    max: 6
  3:
    min: 5
    max: 9
  4:
    min: 6
    max: 10
  5:
    min: 7
    max: 10
  6:
    min: 8
    max: 11
  7:
    min: 9
    max: 12
  8:
    min: 10
    max: 13
  9:
    min: 11
    max: 14
  10:
    min: 12
    max: 14

# 【】クラーディア出現開始時間
cradia_rare_start:
  2012/8/15 15:00:00

raid_battle:
  # クリティカル係数
  critical_fact:
    1.5
  # 神水フラグ
  usable_special_item:
    1
  # 神水係数
  item_fact:
    1.5
  # 使用冒Pリスト
  stamina:
    - 20
    - 40
    - 60
  # 冒P補正
  stamina_correct:
    - 0.3
    - 0.7
    - 1.3

  # 対レイドボス特殊カード
  special_card:
    # ダメージ○倍
    type_damage:
      # アプサラス
      220036: 7
      220036: 8
      220036: 9
      220036: 10
      # スピカ
      220036: 1.5
      220036: 2
      220036: 2.5
      220036: 3
      # ライブラ
      220036: 1.5
      220036: 2
      220036: 2.5
      220036: 3
    # クリティカル○倍
    type_critical:
      # ビーストテイマー
      220036: 3
      220036: 4
      220036: 5
      220036: 6

# 報酬
reward:
  # 回復MP (回復量: 確率)
  recover_mp:
    10: 90
    20: 9
    30: 1

  # クラーディア＆クラーディア＋
  smash_cradia:
    array:
      3:
        type: virtual_money
        cnt: 10000
      5:
        type: gacha_p
        cnt: 1000
      10:
        type: item
        id: 2
        cnt: 2
      20:
        type: item
        id: 2
        cnt: 3
      30:
        type: card
        id: 612
        cnt: 1
      40:
        type: item
        id: 2
        cnt: 4
      50:
        type: card
        id: 220036
        cnt: 1
    repeat:
      start: 60
      interval: 10
      reward:
        type: item
        id: 2
        cnt: 3

  # 【】クラーディア
  smash_cradia_rare:
    array:
      1:
        type: card
        id: 220036
        cnt: 1
      2:
        type: card
        id: 220036
        cnt: 1
      3:
        type: card
        id: 220036
        cnt: 1
      4:
        type: card
        id: 220036
        cnt: 1
    repeat:
      start: 5
      interval: 1
      reward:
        type: item
        id: 2
        cnt: 3

   # 粋
  smash_iki:
    array:
      10:
        type: card
        id: 220036
        cnt: 1
    repeat:
      start: 1
      interval: 1
      reward:
        type: gacha_p
        cnt: 1000

  quest_boss:
    area_id: 10
    quest_id: 10
    comment: '深海の狂宴 第100層クリア報酬です。'
    reward:
      - type: card
        id: 220036
        cnt: 1