---
driver_options:
  MYSQL_ATTR_DIRECT_QUERY: true
database:
  dbhosts:
    yggdrasill:
      hostname: host_ip
      dbname: db_name
      dbuser: db_user
      dbpass: db_pass
    yggdrasill2:
      hostname: host_ip
      dbname: db_name
      dbuser: db_user
      dbpass: db_pass
    yggdrasill3:
      hostname: host_ip
      dbname: db_name
      dbuser: db_user
      dbpass: db_pass
    yggdrasill4:
      hostname: host_ip
      dbname: db_name
      dbuser: db_user
      dbpass: db_pass
  tables:
    # yggdrasill
    adventure_area_mst: yggdrasill
    adventure_monster_mst: yggdrasill
    adventure_quest_mst: yggdrasill
    android_nonce: yggdrasill
    android_sales: yggdrasill
    attr_cnt: yggdrasill
    banner_mst: yggdrasill
    campaign_start_dash: yggdrasill
    event_button_mst: yggdrasill
    event_log: yggdrasill
    event_mst: yggdrasill
    gc_log: yggdrasill
    greeting_data: yggdrasill
    guild_bbs: yggdrasill
    guild_data: yggdrasill
    guild_join_subscription_data: yggdrasill
    guild_role_data: yggdrasill
    guild_role_mst: yggdrasill
    guild_scout_board_setup: yggdrasill
    guild_scout_subscription_data: yggdrasill
    guild_shogo_data: yggdrasill
    guild_shogo_mst: yggdrasill
    guild_user_data: yggdrasill
    information_guild: yggdrasill
    information_managerial: yggdrasill
    information_personal: yggdrasill
    invite_data: yggdrasill
    invite_event_mst: yggdrasill
    invite_reward_mst: yggdrasill
    invite_monster_chain_mst: yggdrasill
    item_data: yggdrasill
    item_log: yggdrasill
    item_mst: yggdrasill
    market_point: yggdrasill
    market_point_android: yggdrasill
    medal_item_data: yggdrasill
    medal_item_log: yggdrasill
    medal_item_mst: yggdrasill
    mini_tutorial_data: yggdrasill
    mysmon_to_guardian_data: yggdrasill
    opening_quest_data: yggdrasill
    opening_quest_mst: yggdrasill
    opening_quest_state: yggdrasill
    partition_manager: yggdrasill
    payment_log: yggdrasill
    platform_login_history: yggdrasill
    pokelabo_reward: yggdrasill
    pokelabo_reward_2: yggdrasill
    pokelogger: yggdrasill
    pokelogger_data: yggdrasill
    preregist_data: yggdrasill
    purchase_history: yggdrasill
    purchase_money_data: yggdrasill
    purchase_request_history: yggdrasill
    quiz_mst: yggdrasill
    quiz_present_mst: yggdrasill
    stamp_data: yggdrasill
    stamp_data_log: yggdrasill
    stamp_event_mst: yggdrasill
    stamp_reward_mst: yggdrasill
    surveillance_user_data: yggdrasill
    theme_summons_flash_log_1: yggdrasill
    theme_summons_treasure_log_1: yggdrasill
    theme_summons_treasure_mst: yggdrasill
    theme_summons_user_data_1: yggdrasill
    user_account: yggdrasill
    user_data: yggdrasill
    user_login_info: yggdrasill
    user_onetime_event_data: yggdrasill
    user_quiz_state: yggdrasill
    user_session_data: yggdrasill
    user_shogo_data: yggdrasill
    user_shogo_mst: yggdrasill
    user_social_data: yggdrasill
    user_visit_data: yggdrasill
    # yggdrasill2
    cvc_data_1: yggdrasill2
    cvc_rank_data_1: yggdrasill2
    cvc_user_data_1: yggdrasill2
    deck_data: yggdrasill2
    deck_detail_data: yggdrasill2
    gvg_action_history: yggdrasill2
    gvg_aid_effect_data: yggdrasill2
    gvg_aid_history: yggdrasill2
    gvg_battle_history: yggdrasill2
    gvg_battle_history_detail: yggdrasill2
    gvg_card_data: yggdrasill2
    gvg_combo_aid_bonus_data: yggdrasill2
    gvg_combo_aid_data: yggdrasill2
    gvg_combo_bonus_data: yggdrasill2
    gvg_combo_data: yggdrasill2
    gvg_combo_log: yggdrasill2
    gvg_data: yggdrasill2
    gvg_guild_member_encourage: yggdrasill2
    gvg_life_recovery_history: yggdrasill2
    gvg_participating_log: yggdrasill2
    gvg_user_data: yggdrasill2
    ragnarok_data: yggdrasill2
    ragnarok_spectator_log: yggdrasill2
    raid_area_mst: yggdrasill2
    raid_boss_data: yggdrasill2
    raid_boss_mst: yggdrasill2
    raid_cluster_mst: yggdrasill2
    raid_guild_data: yggdrasill2
    raid_monster_mst: yggdrasill2
    raid_quest_mst: yggdrasill2
    raid_rank_distribution_guild: yggdrasill2
    raid_rank_distribution_personal: yggdrasill2
    raid_rareboss_rank_correct_mst: yggdrasill2
    raid_reward_mst: yggdrasill2
    raid_user_data: yggdrasill2
    raid_user_guild_point: yggdrasill2
    raid_user_help_list: yggdrasill2
    raid_user_quest_state: yggdrasill2
    raid_user_smash_cnt: yggdrasill2
    raid_user_treasure_data: yggdrasill2
    user_adventure_event: yggdrasill2
    user_adventure_quest_state: yggdrasill2
    # yggdrasill3
    card_data: yggdrasill3
    card_evol_log: yggdrasill3
    card_merg_log: yggdrasill3
    card_mst: yggdrasill3
    card_sell_log: yggdrasill3
    card_skill_mst: yggdrasill3
    card_warehouse_data: yggdrasill3
    gacha_distribution_log: yggdrasill3
    gacha_hit_log: yggdrasill3
    gacha_log: yggdrasill3
    gacha_mst: yggdrasill3
    gacha_user_data: yggdrasill3
    pictorial_data: yggdrasill3
    skill_data: yggdrasill3
    skill_merg_log: yggdrasill3
    skill_mst: yggdrasill3
    trade_clip: yggdrasill3
    trade_contract_log: yggdrasill3
    trade_entry: yggdrasill3
    trade_wish: yggdrasill3
    # yggdrasill4
    access_log: yggdrasill4
    bbs_all_data: yggdrasill4
    bbs_all_reply_data: yggdrasill4
    error_js_log: yggdrasill4
    friend_list: yggdrasill4
    friend_list_pending: yggdrasill4
    information_compensation: yggdrasill4
    ipcountry_list: yggdrasill4
    lucky_egg_data: yggdrasill4
    lucky_egg_mst: yggdrasill4
    present_data: yggdrasill4
    present_receive_log: yggdrasill4
    rank_clan_data: yggdrasill4
    rank_clan_data_daily: yggdrasill4
    rank_clan_data_monthly: yggdrasill4
    rank_clan_data_weekly: yggdrasill4
    rank_clan_total_daily: yggdrasill4
    rank_clan_total_monthly: yggdrasill4
    rank_clan_total_weekly: yggdrasill4
    rank_clan_total_weekly_interim: yggdrasill4
    rank_personal_data: yggdrasill4
    rank_personal_data_daily: yggdrasill4
    rank_personal_data_weekly: yggdrasill4
    rank_personal_total: yggdrasill4
    rank_personal_total_daily: yggdrasill4
    rank_personal_total_weekly: yggdrasill4
    rank_status_data_daily: yggdrasill4
    rank_status_total_daily: yggdrasill4
    rank_card_data_1: yggdrasill4
    rank_card_data_2: yggdrasill4
    social_bonus_data: yggdrasill4
    admin_user: yggdrasill4
    admin_notification: yggdrasill4
    admin_change_name_log: yggdrasill4
    urls: yggdrasill4
    cms_landing_pages: yggdrasill4
    campaign_code: yggdrasill4
    gacha_multi: yggdrasill4
    gacha_config: yggdrasill4
    card_merg_config: yggdrasill4
    maintenance: yggdrasill4
    saturation_log: yggdrasill4
    amazon_sales: yggdrasill4
...
