# 合成設定
card_merg:
  merg_per_up:
    start: "2012-08-06 11:00"
    end: "2013-01-31 20:00"
    merg_per: 2.25
    disp_merg_per: 1.5

  # 常駐経験値確率アップ
  default_merg_per_up:
    start: "2012-07-06 20:00"
    merg_per: 1.5
    no_disp_merg_per: 1
    disp_merg_per: 0
