# メダルショップ設定
medal_shop:
  # 定義名:
  #  start: 開始日時
  #                  20yy-m-d h:i で指定（php date に準拠）
  #                  m は 05 、 5 どっちでもＯＫ
  #                  d は 05 、 5 どっちでもＯＫ
  #                  h:i でも h:i:s どっちでもＯＫ
  #         省略時は制限無し
  #  start_tutorial_end: 1 を書くと、チュートリアル終了後からイベントが始まるようになります
  #                start: も定義している場合は、start と start_tutorial_end でより遅い方が採用されるようになります
  #                start 日時時点でチュートリアル済みの人は、start 日時よりイベント開始
  #                start 日時時点でチュートリアル未完の人は、チュートリアル終了後からイベント開始になります
  #  end: 終了日時
  #                  20yy-m-d h:i で指定（php date に準拠）
  #       省略時は制限無し
  #       end_add が設定されている場合は、end_add を参照します
  #  end_add: 開始日時からのオフセットで終了日時を指定
  #                  +n day で指定（php strtotime に準拠）
  #                  +n week で週単位も可
  #       省略時は制限無し
  #       end が設定されている場合は、end 設定が優先されます
  #  enable_count: 1～ 購入可能数
  #                省略時は個数制限無し
  #  serifu: お店のお姉ちゃんのセリフをイベント用に置き換えられます
  #  item_list: 指定アイテムリスト定義
  #    1: ←適当にユニーク名を振る　省略不可
  #      id: 対象アイテムの item_mst_id を指定　省略不可
  #      purchase_money: 変更後の価格を指定　省略時価格変更無し
  #
  #  ringmenu_img: リングメニューバナー画像指定
  #       省略時はバナーが出ません
  #       複数のイベントが重なった場合は、設定ファイルで上に宣言されているものが優先されます
  #


  # サンプルイベント
  event1:
    start: "2012-08-13 17:50"
    end: "2012-08-20 22:59"
    medal_item_list:
      # 期間限定アイテムセット
      -
        id: 1
        limit_num: 3
        can_buy: 1
