---
cache:
  default:
    engine: Apc
    setting:
      ttl: 3600
  memcache:
    engine: Memcache
    setting:
      prefix: dev$
      ttl: 0
      hosts:
        - { hostname: localhost, port: 11211 }
  dbaccess_cache:
    engine: Apc
    setting:
      prefix: dev$
      ttl: 3600
      hosts:
      - host: localhost
        port: "12001"
  network_global_lock:
    engine: Memcache
    setting:
      prefix: dev$
      ttl: 10
      hosts:
        - { hostname: localhost, port: 11211 }
...
