#####################################
###########<<  総合報酬  >>############
#####################################

# レイド報酬有効？
enable: 1

# 配布番号
# 【注意点】：後半のキーとかぶっちゃだめよ！
compensation:
  # 総合個人ランキング
  type_personal_ranker: 171114125
  # 総合個人キリ番
  type_personal_just: 171114126
  # 総合騎士団ランキング
  type_guild_ranker: 171114127
  # 神水変換
  type_item_change: 171114128
  # 受け取り有効期間
  valid_time: '2014/12/13 00:00:00 '
display_card_ids:
  # 大陸警備団長トゥナイト(SSR)
  - 350276
  # 勇援の堕天使イポス(SSR)
  - 140265
display_card_ids_personal:
  # 大陸警備団長トゥナイト(SSR)
  - 350276
  # 勇援の堕天使イポス(SSR)
  - 140265
display_card_ids_guild:
  # 大陸警備団長トゥナイト(SSR)
  - 350276
  # 勇援の堕天使イポス(SSR)
  - 140265

# 報酬配布時コメントの置換に使用
event_name: 'Mission!'

# 総合個人
personal:
  ranker:
    # 1~10位
    10:
      rank_title: 'Rangs 1-10'
      subject: 'Mission! Récompenses pour classement personnel 1-10'
      body: 'Mission!  <br/>Récompenses pour classement personnel 1-10.'
      comment: 'Mission! Récompenses pour classement personnel 1-10.'
      items:
        # SSR以上確定レアチケ
        - type: item
          id: 2377
          cnt: 1
        # SR以上確定レアチケ
        - type: card
          id: 350276
          cnt: 1
        # SR以上確定レアチケ
        - type: item
          id: 2378
          cnt: 1

    # 11-50位
    50:
      rank_title: 'Rangs 11-50'
      subject: 'Mission! Récompenses pour classement personnel 11-50'
      body: 'Mission! <br/>Récompenses pour classement personnel 11-50.'
      comment: 'Mission! Récompenses pour classement personnel 11-50.'
      items:
        # SSR以上確定レアチケ
        - type: item
          id: 2378
          cnt: 1
        # HR以上確定レアチケ
        - type: card
          id: 350276
          cnt: 1
        # HR以上確定レアチケ
        - type : item
          id: 7
          cnt: 1
    # 51-150位
    150:
      rank_title: 'Rangs 51-150'
      subject: 'Mission! Récompenses pour classement personnel 51-150'
      body: 'Mission! <br/>Récompenses pour classement personnel 51-150.'
      comment: 'Mission! Récompenses pour classement personnel 51-150.'
      items:
        # 黒衣の千年卿ガダーヴル(SR)
        - type: card
          id: 350276
          cnt: 1
        # HR以上確定レアチケ
        - type: item
          id: 7
          cnt: 1
    # 151-500位
    500:
      rank_title: 'Rangs 151-500'
      subject: 'Mission! Récompenses pour classement personnel 151-500'
      body: 'Mission!  <br/>Récompenses pour classement personnel 151-500.'
      comment: 'Mission! Récompenses pour classement personnel 151-500.'
      items:
        # マグネス・ベルネット(SR)
        - type: card
          id: 350276
          cnt: 1
        # HR以上確定レアチケ
        - type: item
          id: 1
          cnt: 1
    # 501-1500位
    1500:
      rank_title: 'Rangs 501-1500'
      subject: 'Mission! Récompenses pour classement personnel 501-1500'
      body: 'Mission!  <br/>Récompenses pour classement personnel 501-1500.'
      comment: 'Mission! Récompenses pour classement personnel 501-1500.'
      items:
        # タール・シュロフ(SR)
        - type: item
          id: 7
          cnt: 1
        # レアチケ
        - type: item
          id: 1
          cnt: 1
    # 1501-5000位
    5000:
      rank_title: 'Rangs 1501-5000'
      subject: 'Mission! Récompenses pour classement personnel 1501-5000'
      body: 'Mission!  <br/>Récompenses pour classement personnel 1501-5000.'
      comment: 'Mission! Récompenses pour classement personnel 1501-5000.'
      items:
        # レアチケ
        - type: item
          id: 1
          cnt: 1
#     # 2001位以下
#    -1:
#      rank_title: 'Above 2001'
#      subject: 'Nightmare Circus  Reward for 2001 or higher Place in Total Personal Ranking'
#      body: 'Nightmare Circus  Reward for 2001 or higher Place in Total Personal Ranking.'
#      comment: 'Nightmare Circus  Reward for 2001 or higher Place in Total Personal Ranking.'
#      items:
#        # ギル
#        - type: virtual_money
#          id : 0
#          cnt : 10000

#総合個人ランキング キリ番
  just:
    333:
      subject: 'Mission! Récompenses pour classement personnel - Chiffre porte-bonheur 333'
      body: 'Mission! <br/>Récompenses pour classement personnel - Chiffre porte-bonheur 333.'
      comment: 'Mission! Récompenses pour classement personnel - Chiffre porte-bonheur 333.'
      items:
        # SSR以上確定レアチケ
        - type: card
          id: 350276
          cnt: 1
    555:
      subject: 'Mission! Récompenses pour classement personnel - Chiffre porte-bonheur 555'
      body: 'Mission!  <br/>Récompenses pour classement personnel - Chiffre porte-bonheur 555.'
      comment: 'Mission! Récompenses pour classement personnel - Chiffre porte-bonheur 555.'
      items:
        # SSR以上確定レアチケ
        - type: card
          id: 350276
          cnt: 1
    1111:
      subject: 'Mission! Récompenses pour classement personnel - Chiffre porte-bonheur 1111'
      body: 'Mission!  <br/>Récompenses pour classement personnel - Chiffre porte-bonheur 1111.'
      comment: 'Mission! Récompenses pour classement personnel - Chiffre porte-bonheur 1111.'
      items:
        # SSR以上確定レアチケ
        - type: card
          id: 350276
          cnt: 1
    2222:
      subject: 'Mission! Récompenses pour classement personnel - Chiffre porte-bonheur 2222'
      body: 'Mission! <br/>Récompenses pour classement personnel - Chiffre porte-bonheur 2222.'
      comment: 'Mission! Récompenses pour classement personnel - Chiffre porte-bonheur 2222.'
      items:
        # SSR以上確定レアチケ
        - type: card
          id: 350276
          cnt: 1
    3333:
      subject: 'Mission! Récompenses pour classement personnel - Chiffre porte-bonheur 3333'
      body: 'Mission!  <br/>Récompenses pour classement personnel - Chiffre porte-bonheur 3333.'
      comment: 'Mission! Récompenses pour classement personnel - Chiffre porte-bonheur 3333.'
      items:
        # SSR以上確定レアチケ
        - type: card
          id: 350276
          cnt: 1
# クラン
guild:
  ranker:
    # 1位
    1:
      bottom: 100000
      rank_title: 'Rang 1'
      subject: 'Mission! Récompenses pour classement de guilde 1'
      body: 'Mission!  <br/>Récompenses pour classement de guilde 1.'
      comment: 'Mission! Récompenses pour classement de guilde 1.'
      items:
        # SSR以上確定レアチケ
        - type: item
          id: 2377
          cnt: 1
    # 2~4位
    4:
      bottom: 100000
      rank_title: 'Rangs 2-4'
      subject: 'Mission! Récompenses pour classement de guilde 2-4'
      body: 'Mission!  <br/>Récompenses pour classement de guilde 2-4.'
      comment: 'Mission! Récompenses pour classement de guilde 2-4.'
      items:
        # 黒衣の千年卿ガダーヴル(SR)
        - type: item
          id: 2378
          cnt: 1
    # 5~50位
    50:
      bottom: 100000
      rank_title: 'Rangs 5-50'
      subject: 'Mission! Récompenses pour classement de guilde 5-50'
      body: 'Mission! <br/>Récompenses pour classement de guilde 5-50.'
      comment: 'Mission! Récompenses pour classement de guilde 5-50.'
      items:
        # 黒衣の千年卿ガダーヴル(SR)
        - type: card
          id: 350276
          cnt: 1
    # 51~300位
    300:
      bottom: 1000
      rank_title: 'Rangs 51-300'
      subject: 'Mission! Récompenses pour classement de guilde 51-300'
      body: 'Mission! <br/>Récompenses pour classement de guilde 51-300.'
      comment: 'Mission! Récompenses pour classement de guilde 51-300.'
      items:
        # マグネス・ベルネット(SR)
        - type: card
          id: 140265
          cnt: 1
#    # 301〜
#    -1:
#      rank_title: 'Above 301'
#      subject: 'Nightmare Circus  Reward for 301 or higher Place in Total Guild Ranking'
#      body: 'Nightmare Circus  Reward for 301 or higher Place in Total Guild Ranking'
#      comment: 'Nightmare Circus  Reward for 301 and higher Place in Total Guild Ranking'
#      items:
#        # レアチケ
#        - type: item
#          id: 1
#          cnt: 1

#秘薬を霊水へ変更
change:
  subject: 'Echangez vos Filets Electromagnétiques contre des Potions de Stamina'
  body: 'Vous avez échangé vos Filets Electromagnétiques contre des Potions de Stamina.'
  comment: 'Vous avez échangé vos Filets Electromagnétiques contre des Potions de Stamina.'
  items:
    - type: item
      id: 2
      cnt: 1
      # cnt を入れるべし

#宝箱が作られてないユーザーの一括報酬配布
trouble_reward:
  reward_mst: 
    #boss_type:0 レアボス
    0:
      #reward_type:1 最多ダメージ
      1:
        type: item
        id: 5
        cnt: 1
      #reward_type:2 攻撃者
      2:
        type: card
        id: 612
        cnt: 1
      #reward_type:3 発見者
      3:
        type: item
        id: 5
        cnt: 1
      #reward_type:4 撃破者
      4:
        type: item
        id: 6
        cnt: 1
    #boss_type:1 ノーマルボス
    1:
      #reward_type:1 最多ダメージ
      1:
        type: item
        id: 5
        cnt: 1
      #reward_type:2 攻撃者
      2:
        type: gacha_p
        id: 0
        cnt: 200
      #reward_type:3 発見者
      3:
        type: virtual_money
        id: 0
        cnt: 2000
      #reward_type:4 撃破者
      4:
        type: item
        id: 6
        cnt: 1
    #boss_type:2 ノーマルボス
    2:
      #reward_type:1 最多ダメージ
      1:
        type: item
        id: 5
        cnt: 1
      #reward_type:2 攻撃者
      2:
        type: gacha_p
        id: 0
        cnt: 200
      #reward_type:3 発見者
      3:
        type: virtual_money
        id: 0
        cnt: 2000
      #reward_type:4 撃破者
      4:
        type: item
        id: 6
        cnt: 1
    #boss_type:3 ノーマルボス
    3:
      #reward_type:1 最多ダメージ
      1:
        type: item
        id: 5
        cnt: 1
      #reward_type:2 攻撃者
      2:
        type: gacha_p
        id: 0
        cnt: 200
      #reward_type:3 発見者
      3:
        type: virtual_money
        id: 0
        cnt: 2000
      #reward_type:4 撃破者
      4:
        type: item
        id: 6
        cnt: 1
    #boss_type:4 裏ボス
    4:
      #reward_type:1 最多ダメージ
      1:
        type: item
        id: 7
        cnt: 1
      #reward_type:2 攻撃者
      2:
        type: card
        id: 613
        cnt: 1
      #reward_type:3 発見者
      3:
        type: item
        id: 4
        cnt: 1
      #reward_type:4 撃破者
      4:
        type: item
        id: 36
        cnt: 1
    #boss_type:5 ボーナスボス
    5:
      #reward_type:1 最多ダメージ
      1:
        type: item
        id: 1
        cnt: 1
      #reward_type:2 攻撃者
      2:
        type: card
        id: 612
        cnt: 1
      #reward_type:3 発見者
      3:
        type: item
        id: 5
        cnt: 1
      #reward_type:4 撃破者
      4:
        type: item
        id: 6
        cnt: 1
