#####################################
###########<<  総合報酬  >>############
#####################################

# レイド報酬有効？
enable: 1

# 配布番号
# 【注意点】：後半のキーとかぶっちゃだめよ！
compensation:
  # 総合個人ランキング
  type_personal_ranker: 171114100
  # 総合個人キリ番
  type_personal_just: 171114101
  # 総合騎士団ランキング
  type_guild_ranker: 171114102
  # 神水変換
  type_item_change: 171114103
  # 受け取り有効期間
  valid_time: '2014/12/13 00:00:00 '
display_card_ids:
  # 大陸警備団長トゥナイト(SSR)
  - 350276
  # 勇援の堕天使イポス(SSR)
  - 140265
display_card_ids_personal:
  # 大陸警備団長トゥナイト(SSR)
  - 350276
  # 勇援の堕天使イポス(SSR)
  - 140265
display_card_ids_guild:
  # 大陸警備団長トゥナイト(SSR)
  - 350276
  # 勇援の堕天使イポス(SSR)
  - 140265

# 報酬配布時コメントの置換に使用
event_name: 'Fugitive Escaping'

# 総合個人
personal:
  ranker:
    # 1~10位
    10:
      rank_title: '1-10 Place'
      subject: 'Fugitive Escaping Reward for 1-10 Place in Total Personal Ranking'
      body: 'Fugitive Escaping  <br/>Reward for 1-10 Place in Total Personal Ranking.'
      comment: 'Fugitive Escaping Reward for 1-10 Place in Total Personal Ranking.'
      items:
        # SSR以上確定レアチケ
        - type: item
          id: 2281
          cnt: 1
        # SR以上確定レアチケ
        - type: card
          id: 350276
          cnt: 1
        # SR以上確定レアチケ
        - type: item
          id: 2282
          cnt: 1

    # 11-50位
    50:
      rank_title: '11-50 Place'
      subject: 'Fugitive Escaping Reward for 11-50 Place in Total Personal Ranking'
      body: 'Fugitive Escaping <br/>Reward for 11-50 Place in Total Personal Ranking.'
      comment: 'Fugitive Escaping Reward for 11-50 Place in Total Personal Ranking.'
      items:
        # SSR以上確定レアチケ
        - type: item
          id: 2282
          cnt: 1
        # HR以上確定レアチケ
        - type: card
          id: 350276
          cnt: 1
        # HR以上確定レアチケ
        - type : item
          id: 7
          cnt: 1
    # 51-150位
    150:
      rank_title: '51-150 Place'
      subject: 'Fugitive Escaping Reward for 51-150 Place in Total Personal Ranking'
      body: 'Fugitive Escaping <br/>Reward for 51-150 Place in Total Personal Ranking.'
      comment: 'Fugitive Escaping Reward for 51-150 Place in Total Personal Ranking.'
      items:
        # 黒衣の千年卿ガダーヴル(SR)
        - type: card
          id: 350276
          cnt: 1
        # HR以上確定レアチケ
        - type: item
          id: 7
          cnt: 1
    # 151-500位
    500:
      rank_title: '151-500 Place'
      subject: 'Fugitive Escaping Reward for 151-500 Place in Total Personal Ranking'
      body: 'Fugitive Escaping  <br/>Reward for 151-500 Place in Total Personal Ranking.'
      comment: 'Fugitive Escaping Reward for 151-500 Place in Total Personal Ranking.'
      items:
        # マグネス・ベルネット(SR)
        - type: card
          id: 350276
          cnt: 1
        # HR以上確定レアチケ
        - type: item
          id: 1
          cnt: 1
    # 501-1500位
    1500:
      rank_title: '501-1500 Place'
      subject: 'Fugitive Escaping Reward for 501-1500 Place in Total Personal Ranking'
      body: 'Fugitive Escaping  <br/>Reward for 501-1500 Place in Total Personal Ranking.'
      comment: 'Fugitive Escaping Reward for 501-1500 Place in Total Personal Ranking.'
      items:
        # タール・シュロフ(SR)
        - type: item
          id: 7
          cnt: 1
        # レアチケ
        - type: item
          id: 1
          cnt: 1
    # 1501-5000位
    5000:
      rank_title: '1501-5000 Place'
      subject: 'Fugitive Escaping Reward for 1501-5000 Place in Total Personal Ranking'
      body: 'Fugitive Escaping  <br/>Reward for 1501-5000 Place in Total Personal Ranking.'
      comment: 'Fugitive Escaping Reward for 1501-5000 Place in Total Personal Ranking.'
      items:
        # レアチケ
        - type: item
          id: 1
          cnt: 2
#     # 2001位以下
#    -1:
#      rank_title: 'Above 2001'
#      subject: 'Nightmare Circus  Reward for 2001 or higher Place in Total Personal Ranking'
#      body: 'Nightmare Circus  Reward for 2001 or higher Place in Total Personal Ranking.'
#      comment: 'Nightmare Circus  Reward for 2001 or higher Place in Total Personal Ranking.'
#      items:
#        # ギル
#        - type: virtual_money
#          id : 0
#          cnt : 10000

#総合個人ランキング キリ番
  just:
    333:
      subject: 'Fugitive Escaping Reward for Lucky 333 Place in Total Personal Ranking'
      body: 'Fugitive Escaping <br/>Reward for Lucky 333 Place in Total Personal Ranking.'
      comment: 'Fugitive Escaping Reward for Lucky 333 Place in Total Personal Ranking.'
      items:
        # SSR以上確定レアチケ
        - type: card
          id: 350276
          cnt: 1
    555:
      subject: 'Fugitive Escaping Reward for Lucky 555 Place in Total Personal Ranking'
      body: 'Fugitive Escaping  <br/>Reward for Lucky 555 Place in Total Personal Ranking.'
      comment: 'Fugitive Escaping Reward for Lucky 555 Place in Total Personal Ranking.'
      items:
        # SSR以上確定レアチケ
        - type: card
          id: 350276
          cnt: 1
    1111:
      subject: 'Fugitive Escaping Reward for Lucky 1111 Place in Total Personal Ranking'
      body: 'Fugitive Escaping  <br/>Reward for Lucky 1111 Place in Total Personal Ranking.'
      comment: 'Fugitive Escaping Reward for Lucky 1111 Place in Total Personal Ranking.'
      items:
        # SSR以上確定レアチケ
        - type: card
          id: 350276
          cnt: 1
    2222:
      subject: 'Fugitive Escaping Reward for Lucky 2222 Place in Total Personal Ranking'
      body: 'Fugitive Escaping <br/>Reward for Lucky 2222 Place in Total Personal Ranking.'
      comment: 'Fugitive Escaping Reward for Lucky 2222 Place in Total Personal Ranking.'
      items:
        # SSR以上確定レアチケ
        - type: card
          id: 350276
          cnt: 1
    3333:
      subject: 'Fugitive Escaping Reward for Lucky 3333 Place in Total Personal Ranking'
      body: 'Fugitive Escaping  <br/>Reward for Lucky 3333 Place in Total Personal Ranking.'
      comment: 'Fugitive Escaping Reward for Lucky 3333 Place in Total Personal Ranking.'
      items:
        # SSR以上確定レアチケ
        - type: card
          id: 350276
          cnt: 1
# クラン
guild:
  ranker:
    # 1位
    1:
      bottom: 100000
      rank_title: '1 Place'
      subject: 'Fugitive Escaping Reward for 1 Place in Total Guild Ranking'
      body: 'Fugitive Escaping  <br/>Reward for 1 Place in Total Guild Ranking.'
      comment: 'Fugitive Escaping Reward for 1 Place in Total Guild Ranking.'
      items:
        # SSR以上確定レアチケ
        - type: item
          id: 2281
          cnt: 1
    # 2~4位
    4:
      bottom: 100000
      rank_title: '2-4 Place'
      subject: 'Fugitive Escaping Reward for 2-4 Place in Total Guild Ranking'
      body: 'Fugitive Escaping  <br/>Reward for 2-4 Place in Total Guild Ranking.'
      comment: 'Fugitive Escaping Reward for 2-4 Place in Total Guild Ranking.'
      items:
        # 黒衣の千年卿ガダーヴル(SR)
        - type: item
          id: 2282
          cnt: 1
    # 5~50位
    50:
      bottom: 100000
      rank_title: '5-50 Place'
      subject: 'Fugitive Escaping Reward for 5-50 Place in Total Guild Ranking'
      body: 'Fugitive Escaping <br/>Reward for 5-50 Place in Total Guild Ranking.'
      comment: 'Fugitive Escaping Reward for 5-50 Place in Total Guild Ranking.'
      items:
        # 黒衣の千年卿ガダーヴル(SR)
        - type: card
          id: 350276
          cnt: 1
    # 51~300位
    300:
      bottom: 1000
      rank_title: '51-300 Place'
      subject: 'Fugitive Escaping Reward for 51-300 Place in Total Guild Ranking'
      body: 'Fugitive Escaping <br/>Reward for 51-300 Place in Total Guild Ranking.'
      comment: 'Fugitive Escaping Reward for 51-300 Place in Total Guild Ranking.'
      items:
        # マグネス・ベルネット(SR)
        - type: card
          id: 140265
          cnt: 1
#    # 301〜
#    -1:
#      rank_title: 'Above 301'
#      subject: 'Nightmare Circus  Reward for 301 or higher Place in Total Guild Ranking'
#      body: 'Nightmare Circus  Reward for 301 or higher Place in Total Guild Ranking'
#      comment: 'Nightmare Circus  Reward for 301 and higher Place in Total Guild Ranking'
#      items:
#        # レアチケ
#        - type: item
#          id: 1
#          cnt: 1

#秘薬を霊水へ変更
change:
  subject: 'Exchange of Electromagnetic Supernet for Stamina Potion.'
  body: 'You exchanged Electromagnetic Supernet for Stamina Potion.'
  comment: 'You exchanged Electromagnetic Supernet for Stamina Potion.'
  items:
    - type: item
      id: 2
      cnt: 1
      # cnt を入れるべし

#宝箱が作られてないユーザーの一括報酬配布
trouble_reward:
  reward_mst: 
    #boss_type:0 レアボス
    0:
      #reward_type:1 最多ダメージ
      1:
        type: item
        id: 5
        cnt: 1
      #reward_type:2 攻撃者
      2:
        type: card
        id: 612
        cnt: 1
      #reward_type:3 発見者
      3:
        type: item
        id: 5
        cnt: 1
      #reward_type:4 撃破者
      4:
        type: item
        id: 6
        cnt: 1
    #boss_type:1 ノーマルボス
    1:
      #reward_type:1 最多ダメージ
      1:
        type: item
        id: 5
        cnt: 1
      #reward_type:2 攻撃者
      2:
        type: gacha_p
        id: 0
        cnt: 200
      #reward_type:3 発見者
      3:
        type: virtual_money
        id: 0
        cnt: 2000
      #reward_type:4 撃破者
      4:
        type: item
        id: 6
        cnt: 1
    #boss_type:2 ノーマルボス
    2:
      #reward_type:1 最多ダメージ
      1:
        type: item
        id: 5
        cnt: 1
      #reward_type:2 攻撃者
      2:
        type: gacha_p
        id: 0
        cnt: 200
      #reward_type:3 発見者
      3:
        type: virtual_money
        id: 0
        cnt: 2000
      #reward_type:4 撃破者
      4:
        type: item
        id: 6
        cnt: 1
    #boss_type:3 ノーマルボス
    3:
      #reward_type:1 最多ダメージ
      1:
        type: item
        id: 5
        cnt: 1
      #reward_type:2 攻撃者
      2:
        type: gacha_p
        id: 0
        cnt: 200
      #reward_type:3 発見者
      3:
        type: virtual_money
        id: 0
        cnt: 2000
      #reward_type:4 撃破者
      4:
        type: item
        id: 6
        cnt: 1
    #boss_type:4 裏ボス
    4:
      #reward_type:1 最多ダメージ
      1:
        type: item
        id: 7
        cnt: 1
      #reward_type:2 攻撃者
      2:
        type: card
        id: 613
        cnt: 1
      #reward_type:3 発見者
      3:
        type: item
        id: 4
        cnt: 1
      #reward_type:4 撃破者
      4:
        type: item
        id: 36
        cnt: 1
    #boss_type:5 ボーナスボス
    5:
      #reward_type:1 最多ダメージ
      1:
        type: item
        id: 1
        cnt: 1
      #reward_type:2 攻撃者
      2:
        type: card
        id: 612
        cnt: 1
      #reward_type:3 発見者
      3:
        type: item
        id: 5
        cnt: 1
      #reward_type:4 撃破者
      4:
        type: item
        id: 6
        cnt: 1
