#####################################
###########<<  後半報酬  >>############
#####################################

# レイド報酬有効？
enable: 1

# 配布番号
# 【注意点】：総合のキーとかぶっちゃだめよ！
compensation:
  # 後半個人ランキング
  type_personal_ranker: 140130100
  # 後半個人キリ番
  type_personal_just: 140130101
  # 後半騎士団ランキング
  type_guild_ranker: 140130102
  # 神水変換
  type_item_change: 140130103
  # 受け取り有効期間
  valid_time: '2014/02/06 23:59'
  
display_card_ids:
  # 大陸警備団長トゥナイト(SSR)
  - 360224
  # 勇援の堕天使イポス(SSR)
  - 160210
  # 黒衣の千年卿ガダーヴル(SR)
  - 350223
  # タール・シュロフ(SR)
  - 140209
  # マグネス・ベルネット(SR)
  - 150208
  # 狂気に満ちし殺戮者 J(HR)
  - 240205
  
display_card_ids_personal:
  # 大陸警備団長トゥナイト(SSR)
  - 360224
  # 勇援の堕天使イポス(SSR)
  - 160210
  # 黒衣の千年卿ガダーヴル(SR)
  - 350223
  # タール・シュロフ(SR)
  - 140209
  # マグネス・ベルネット(SR)
  - 150208
  # 狂気に満ちし殺戮者 J(HR)
  - 240205
  
display_card_ids_guild:
  # 大陸警備団長トゥナイト(SSR)
  - 360224
  # 勇援の堕天使イポス(SSR)
  - 160210
  # 黒衣の千年卿ガダーヴル(SR)
  - 350223
  # タール・シュロフ(SR)
  - 140209
  # マグネス・ベルネット(SR)
  - 150208
  # 狂気に満ちし殺戮者 J(HR)
  - 240205

# 報酬配布時コメントの置換に使用
event_name: '選勇たちの血戦'

# 後半個人
personal:
  ranker:
    # 1~10位
    10:
      rank_title: '1~10位'
      subject: '選勇たちの血戦 後半個人ランキング1~10位報酬'
      body: '選勇たちの血戦 <br/>後半個人ランキング1~10位報酬です。'
      comment: '選勇たちの血戦 後半個人ランキング1~10位報酬です。'
      items:
        # 勇援の堕天使イポス(SSR)
        - type: card
          id: 160210
          cnt: 1
        # SR以上確定レアチケ
        - type: item
          id : 8
          cnt : 1
    # 11-100位
    100:
      rank_title: '11〜100位'
      subject: '選勇たちの血戦 後半個人ランキング11〜100位報酬'
      body: '選勇たちの血戦 <br/>後半個人ランキング11〜100位報酬です。'
      comment: '選勇たちの血戦 後半個人ランキング11〜100位報酬です。'
      items:
        # 勇援の堕天使イポス(SSR)
        - type: card
          id: 160210
          cnt: 1
        # HR以上確定レアチケ
        - type: item
          id : 7
          cnt : 1
    # 101-200位
    200:
      rank_title: '101-200位'
      subject: '選勇たちの血戦 後半個人ランキング101-200位報酬'
      body: '選勇たちの血戦 <br/>後半個人ランキング101-200位報酬です。'
      comment: '選勇たちの血戦 後半個人ランキング101-200位報酬です。'
      items:
        # SR以上確定レアチケ
        - type: item
          id : 8
          cnt : 1
        # HR以上確定レアチケ
        - type: item
          id : 7
          cnt : 1
    # 201-500位
    500:
      rank_title: '201-500位'
      subject: '選勇たちの血戦 後半個人ランキング201-500位報酬'
      body: '選勇たちの血戦 <br/>後半個人ランキング201-500位報酬です。'
      comment: '選勇たちの血戦 後半個人ランキング201-500位報酬です。'
      items:
        # SR以上確定レアチケ
        - type: item
          id : 8
          cnt : 1
        # レアチケ
        - type: item
          id : 1
          cnt : 2
    # 501-1000位
    1000:
      rank_title: '501-1000位'
      subject: '選勇たちの血戦 後半個人ランキング501-1000位報酬'
      body: '選勇たちの血戦 <br/>後半個人ランキング501-1000位報酬です。'
      comment: '選勇たちの血戦 後半個人ランキング501-1000位報酬です。'
      items:
        # HR以上確定レアチケ
        - type: item
          id : 7
          cnt : 1
        # レアチケ
        - type: item
          id : 1
          cnt : 2
    # 1001-2000位
    2000:
      rank_title: '1001-2000位'
      subject: '選勇たちの血戦 後半個人ランキング1001-2000位報酬'
      body: '選勇たちの血戦 <br/>後半個人ランキング1001-2000位報酬です。'
      comment: '選勇たちの血戦 後半個人ランキング1001-2000位報酬です。'
      items:
        # HR以上確定レアチケ
        - type: item
          id : 7
          cnt : 1
        # レアチケ
        - type: item
          id : 1
          cnt : 1
    # 2001-5000位
    5000:
      rank_title: '2001-5000位'
      subject: '選勇たちの血戦 後半個人ランキング2001-5000位報酬'
      body: '選勇たちの血戦 <br/>後半個人ランキング2001-5000位報酬です。'
      comment: '選勇たちの血戦 後半個人ランキング2001-5000位報酬です。'
      items:
        # レアチケ
        - type: item
          id : 1
          cnt : 1
        # 「自分用」進撃P全チャージ
        - type: item
          id : 4
          cnt : 3
    # 5001-10000位
    10000:
      rank_title: '5001-10000位'
      subject: '選勇たちの血戦 後半個人ランキング5001-10000位報酬'
      body: '選勇たちの血戦 <br/>後半個人ランキング5001-10000位報酬です。'
      comment: '選勇たちの血戦 後半個人ランキング5001-10000位報酬です。'
      items:
        # 「自分用」進撃P全チャージ
        - type: item
          id : 4
          cnt : 3
    # 10001-30000位
    30000:
      rank_title: '10001-30000位'
      subject: '選勇たちの血戦 後半個人ランキング10001-30000位報酬'
      body: '選勇たちの血戦 <br/>後半個人ランキング10001-30000位報酬です。'
      comment: '選勇たちの血戦 後半個人ランキング10001-30000位報酬です。'
      items:
        # 「自分用」進撃P全チャージ
        - type: item
          id : 4
          cnt : 2
    # 30001-50000位
    50000:
      rank_title: '30001-50000位'
      subject: '選勇たちの血戦 後半個人ランキング30001-50000位報酬'
      body: '選勇たちの血戦 <br/>後半個人ランキング30001-50000位報酬です。'
      comment: '選勇たちの血戦 後半個人ランキング30001-50000位報酬です。'
      items:
        # 「自分用」進撃P全チャージ
        - type: item
          id : 4
          cnt : 1
#     # 50001位以下
#    -1:
#      rank_title: '50001以下'
#      subject: '選勇たちの血戦 後半個人ランキング50001位以下報酬'
#      body: '選勇たちの血戦 後半個人ランキング50001位以下報酬です。'
#      comment: '選勇たちの血戦 後半個人ランキング50001位以下報酬です。'
#      items:
#        # ギル
#        - type: virtual_money
#          id : 0
#          cnt : 10000

#後半個人ランキング キリ番
  just:
    333:
      subject: '選勇たちの血戦 後半個人ランキングキリ番333位報酬'
      body: '選勇たちの血戦 <br/>後半個人ランキングキリ番333位報酬です。'
      comment: '選勇たちの血戦 後半個人ランキングキリ番333位報酬です。'
      items:
        # 勇援の堕天使イポス(SSR)
        - type: card
          id: 160210
          cnt: 1
    555:
      subject: '選勇たちの血戦 後半個人ランキングキリ番555位報酬'
      body: '選勇たちの血戦 <br/>後半個人ランキングキリ番555位報酬です。'
      comment: '選勇たちの血戦 後半個人ランキングキリ番555位報酬です。'
      items:
        # 勇援の堕天使イポス(SSR)
        - type: card
          id: 160210
          cnt: 1
    1111:
      subject: '選勇たちの血戦 後半個人ランキングキリ番1111位報酬'
      body: '選勇たちの血戦 <br/>後半個人ランキングキリ番1111位報酬です。'
      comment: '選勇たちの血戦 後半個人ランキングキリ番1111位報酬です。'
      items:
        # 勇援の堕天使イポス(SSR)
        - type: card
          id: 160210
          cnt: 1
    2222:
      subject: '選勇たちの血戦 後半個人ランキングキリ番2222位報酬'
      body: '選勇たちの血戦 <br/>後半個人ランキングキリ番2222位報酬です。'
      comment: '選勇たちの血戦 後半個人ランキングキリ番2222位報酬です。'
      items:
        # 勇援の堕天使イポス(SSR)
        - type: card
          id: 160210
          cnt: 1
    3333:
      subject: '選勇たちの血戦 後半個人ランキングキリ番3333位報酬'
      body: '選勇たちの血戦 <br/>後半個人ランキングキリ番3333位報酬です。'
      comment: '選勇たちの血戦 後半個人ランキングキリ番3333位報酬です。'
      items:
        # 勇援の堕天使イポス(SSR)
        - type: card
          id: 160210
          cnt: 1
# クラン
guild:
  ranker:
    # 1~10位
    10:
      bottom: 100000
      rank_title: '1~10位'
      subject: '選勇たちの血戦 後半騎士団ランキング1~10位報酬'
      body: '選勇たちの血戦 <br/>後半騎士団ランキング1~10位報酬です。'
      comment: '選勇たちの血戦 後半騎士団ランキング1~10位報酬です。'
      items:
        # 勇援の堕天使イポス(SSR)
        - type: card
          id: 160210
          cnt: 1
        # 強化クリスタルLv.3
        - type: card
          id: 614
          cnt: 1
        # 強化クリスタルLv.2
        - type: card
          id: 613
          cnt: 1
        # 強化クリスタルLv.1
        - type: card
          id: 612
          cnt: 1
    # 11~50位
    50:
      bottom: 100000
      rank_title: '11~50位'
      subject: '選勇たちの血戦 後半騎士団ランキング11~50位報酬'
      body: '選勇たちの血戦 <br/>後半騎士団ランキング11~50位報酬です。'
      comment: '選勇たちの血戦 後半騎士団ランキング11~50位報酬です。'
      items:
        # SR以上確定レアチケ
        - type: item
          id : 8
          cnt : 1
        # 強化クリスタルLv.2
        - type: card
          id: 613
          cnt: 1
        # 強化クリスタルLv.1
        - type: card
          id: 612
          cnt: 1
    # 51~100位
    100:
      bottom: 100000
      rank_title: '51~100位'
      subject: '選勇たちの血戦 後半騎士団ランキング51~100位報酬'
      body: '選勇たちの血戦 <br/>後半騎士団ランキング51~100位報酬です。'
      comment: '選勇たちの血戦 後半騎士団ランキング51~100位報酬です。'
      items:
        # SR以上確定レアチケ
        - type: item
          id : 8
          cnt : 1
        # 強化クリスタルLv.2
        - type: card
          id: 613
          cnt: 1
    # 101~300位
    300:
      bottom: 1000
      rank_title: '101~300位'
      subject: '選勇たちの血戦 後半騎士団ランキング101~300位報酬'
      body: '選勇たちの血戦 <br/>後半騎士団ランキング101~300位報酬です。'
      comment: '選勇たちの血戦 後半騎士団ランキング101~300位報酬です。'
      items:
        # HR以上確定レアチケ
        - type: item
          id : 7
          cnt : 1
        # 強化クリスタルLv.1
        - type: card
          id: 612
          cnt: 1
    # 301~1000位
    1000:
      bottom: 1000
      rank_title: '301~1000位'
      subject: '選勇たちの血戦 後半騎士団ランキング301~1000位報酬'
      body: '選勇たちの血戦 <br/>後半騎士団ランキング301~1000位報酬です。'
      comment: '選勇たちの血戦 後半騎士団ランキング301~1000位報酬です。'
      items:
        # 強化クリスタルLv.1
        - type: card
          id: 612
          cnt: 1
#    # 3001〜
#    -1:
#      rank_title: '3001以下'
#      subject: '選勇たちの血戦 後半騎士団ランキング3001位以下報酬'
#      body: '選勇たちの血戦 後半騎士団ランキング3001位以下報酬です'
#      comment: '選勇たちの血戦 後半騎士団ランキング3001位以下報酬です'
#      items:
#        # レアチケ
#        - type: item
#          id: 1
#          cnt: 1

#秘薬を霊水へ変更
change:
  subject: '勇士の結晶から進撃Pチャージへの変換'
  body: '勇士の結晶から進撃Pチャージへの変換しました。'
  comment: '勇士の結晶から進撃Pチャージへの変換しました。'
  items:
    - type: item
      id: 2
      cnt: 1
      # cnt を入れるべし