# memchash_key変更しろよー

conf:
  # 画像ベースフォルダ
  img_base_folder: '/img/raid/2/'
  # 開始時間
  start: 2013/02/08 15:00:00
  # イベント中イメージ
  center_img: '/img/raid/2/title.png'
  # 終了時間
  end:   2013/02/16 23:59:59
  # イベント終了後イメージ
  end_center_img: '/img/raid/2/title.png'
  # 掲載フラグ 0:掲載しない 1:掲載する 終了時間が優先される
  carry_flag: 1
  # 予告期間中センター表示フラグ 0:センター非表示 1:センター表示
  carry_center: 1
  # 掲載イメージ（予告）
  carry_img: '/img/raid/2/title.png'
  # 掲載終了時間 時間が越えたら掲載されない
  carry_end: 2013/02/16 23:59:59
  # リングメニューボタン遷移先URL
  ring_link: '/raid_event/'
  # クエストバナー
  quest_banner: '/img/raid/2/title.png'
  # 残りスタミナによるエンカウント補正閾値
  # 残りスタミナ割合（空=0　～　満タン=1）
  # 段階で数値の低い順に書いてください。
  # 現状３つまで指定可能
  # これより小さい場合にそれぞれの補正を適用
  last_stamina_encount_rate:
    # stamina_appear_rate0
    - 0.1
    # stamina_appear_rate1
    - 0.3
    # stamina_appear_rate2
    - 0.5
  # ポイントランキングを使うか？
  use_point_ranking: 1
#  debug_uids:
#    - 29
#    - 18
#    - 370623
  debug_start: 2013/02/06 00:00:00
  debug_end: 2013/02/16 23:59:59
  # レイドボス出現率アップ期間
  # 期間内かつフラグ0じゃない時にマイページでアニメーションが流れます
  # マイペでのアニメーション再生可否用の設定となります
  boss_appear_up_anim_on_mypage:
    disp_start: 2013/02/10 17:00:00
    disp_end:   2013/02/10 21:59:59
    flag: 1
  # レイド専用アイテム　イベント期間外は
  raid_item:
    # fireworks (what's the number for fireworks, is it still 17?)
    -  17

# 連動１１連召喚
gacha:
  # 連動ガチャあり:1, 連動ガチャなし:0
  # flag:0 の場合gacha_nameが指定されていても無視されます
  # 日付はgacha.yamlの方で見てるから、特にここで指定する必要なし
  flag: 1
  # 該当ガチャの定義名(gacha.yaml内に定義されている定義名を使用)
  gacha_name:
    - 'raid2_eve'
  # 連動ガチャのバナー画像パス
  banner: '/img/banner/banner_11santa.gif'
  # ガチャバナー小
  banner_small: '/img/banner/banner_11santa.gif'

# カード紹介に乗せるリスト
special_cards:
  # Tara
  - 150500
  # Raena
  - 240500

# 特定ボスの出現開始時間制御
# ここで設定されているボスは、start 時間を過ぎるまで出てこないよ
boss_appear_limit:
  type:
    - 4
  start: '2012/02/12 00:00:00'

raid_battle:
  # クリティカル係数
  critical_fact:
    1.5
  # 神水フラグ
  usable_special_item:
    1
  # 使用可能期間は↓のショップ定義と連動させました
  shinsui_shop_def: shinsui_sell
  # 神水係数
  item_fact:
    1.5
  # 使用冒Pリスト
  stamina:
    - 20
    - 40
    - 60
  # 冒P補正
  stamina_correct:
    - 0.3
    - 0.7
    - 1.3
  # 逃亡時使用冒険P
  escape_cost: 20
  # 協力攻撃ボーナス係数
  # 他人が発見したボスを殴った時獲得ポイント係数
  cooperation_damage_bonus:
    1.2

  # 対レイドボス特殊カード
  special_card:
    # 結果ポイント補正
    type_result_point:
#      1226: 1.2
#      1227: 1.2
#      1228: 1.2
#      1229: 1.2
#      # ラビリンス
#      1354: 1.5
#      1355: 1.5
#      1356: 1.5
#      1357: 1.5
#      # ターリア
#      1358: 1.2
#      1359: 1.2
#      1360: 1.2
#      1361: 1.2
    # ダメージ○倍
    type_damage:
      # Tara > [Tiger Master] Tara
      150500: 1.5
      151500: 3
      152500: 5
      159500: 10
      # Rafae > [Rabbit Master] Rafae
      330500: 1.5
      331500: 2
      332500: 2.5
      339500: 5
      # Raena > [Ram Master] Raena
      240500: 1.5
      241500: 3
      242500: 4.5
      249500: 8
      # Beatrice > [Boar Master] Beatrice
      240501: 1.5
      241501: 2
      242501: 2.5
      249501: 5

#    # クリティカル○倍
#    #今回は使用しないけど、値が入ってないとエラーになるのでダミーカードを他カードと同じ1倍で設定
#    type_critical:
#      # パンプキン・プリンセス
#      1181: 1
#      1182: 1
#      1183: 1
#      1184: 1

# 報酬
reward:
  # 回復MP (回復量: 確率)
  recover_mp:
    10: 90
    20: 9
    30: 1
  # 回復冒P (使用冒険P　数値以上判定: 回復冒険P)
  recover_stamina:
    0: 0
    60: 20
    180: 40
  # 特別撃破報酬
  smash_bonus:
    disp_name: 'Зодиак'
    # カウントするボスtype
    type:
      - 1
      - 2
      - 3
#ボス撃破報酬
    array:
      3:
        type: virtual_money
        id: 0
        cnt: 3000
      5:
        type: gacha_p
        id: 0
        cnt: 3000
      10:
        type: item
        id: 4
        cnt: 2
      20:
        type: card
        id: 612
        cnt: 1
      30:
        type: card
        id: 613
        cnt: 1
      40:
        type: item
        id: 4
        cnt: 2
      50:
        type: card
        id: 614
        cnt: 1
    repeat:
      start: 60
      interval: 10
      reward:
        type: item
        id: 4
        cnt: 3


## n階層到達で報酬:　リンダ―レンジャー（R）230060
  quest_boss:
    25:
      comment: 'Пройди 25 квестов, чтобы получить Рафию'
      reward:
        -
          type: card
          id: 330500
          cnt: 1
    50:
      comment: 'Пройди 50 квестов, чтобы получить Рафию'
      reward:
        -
          type: card
          id: 330500
          cnt: 1
    75:
      comment: 'Пройди 75 квестов, чтобы получить Рафию'
      reward:
        -
          type: card
          id: 330500
          cnt: 1
    100:
      comment: 'Пройди 100 квестов, чтобы получить Рафию'
      reward:
        -
          type: card
          id: 330500
          cnt: 1
#  # 討伐お礼
#  present_send:
#    comment: '協力してくれてありがとう。'
#    list:
#      -
#        type: card
#        id: 612
#        cnt: 1
# お礼メッセージデフォルトテキスト
greet:
  default_message:
    # 配列で複数入れておくと、ランダムで選択されます
    - 'С китайским Новым годом!'